export const PRODUCTION_LMS_SCHEMA_VERSION = 2;

export const PRODUCTION_LMS_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS lms_schema_versions (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS lms_identity_profiles (
    account_id TEXT PRIMARY KEY,
    entra_tenant_id TEXT NOT NULL,
    entra_object_id TEXT NOT NULL,
    head_office_customer_number TEXT NOT NULL UNIQUE,
    stripe_customer_id TEXT UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE CASCADE,
    UNIQUE (entra_tenant_id, entra_object_id)
  )`,
  `CREATE TABLE IF NOT EXISTS lms_plans (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    amount_pence INTEGER NOT NULL CHECK (amount_pence > 0),
    currency TEXT NOT NULL DEFAULT 'GBP',
    billing_interval TEXT NOT NULL DEFAULT 'month' CHECK (billing_interval = 'month'),
    seat_limit INTEGER NOT NULL CHECK (seat_limit > 0),
    library_tier TEXT NOT NULL CHECK (library_tier IN ('core', 'complete')),
    stripe_product_id TEXT UNIQUE,
    stripe_price_id TEXT UNIQUE,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS lms_checkout_sessions (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    stripe_checkout_session_id TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'created' CHECK (status IN ('created', 'completed', 'expired', 'failed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES lms_plans(id)
  )`,
  `CREATE TABLE IF NOT EXISTS lms_subscriptions (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    stripe_customer_id TEXT NOT NULL,
    stripe_subscription_id TEXT NOT NULL UNIQUE,
    stripe_checkout_session_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('incomplete', 'incomplete_expired', 'trialing', 'active', 'past_due', 'cancelled', 'unpaid', 'paused')),
    seat_limit INTEGER NOT NULL CHECK (seat_limit > 0),
    current_period_start TEXT,
    current_period_end TEXT,
    cancel_at_period_end INTEGER NOT NULL DEFAULT 0 CHECK (cancel_at_period_end IN (0, 1)),
    cancelled_at TEXT,
    grace_expires_at TEXT,
    last_payment_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES lms_plans(id)
  )`,
  `CREATE TABLE IF NOT EXISTS lms_organisations (
    id TEXT PRIMARY KEY,
    owner_account_id TEXT NOT NULL,
    subscription_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'restricted', 'closed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_account_id) REFERENCES customer_accounts(id) ON DELETE RESTRICT,
    FOREIGN KEY (subscription_id) REFERENCES lms_subscriptions(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS lms_organisation_members (
    id TEXT PRIMARY KEY,
    organisation_id TEXT NOT NULL,
    account_id TEXT,
    invited_email TEXT,
    role TEXT NOT NULL DEFAULT 'learner' CHECK (role IN ('owner', 'administrator', 'manager', 'learner')),
    status TEXT NOT NULL DEFAULT 'invited' CHECK (status IN ('invited', 'active', 'suspended', 'removed')),
    invited_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    joined_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organisation_id) REFERENCES lms_organisations(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS lms_enrolments (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    subscription_id TEXT NOT NULL,
    organisation_id TEXT,
    course_slug TEXT NOT NULL,
    course_code TEXT NOT NULL,
    course_version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'enrolled' CHECK (status IN ('enrolled', 'in_progress', 'assessment_ready', 'completed', 'withdrawn', 'access_suspended')),
    progress_percent INTEGER NOT NULL DEFAULT 0 CHECK (progress_percent BETWEEN 0 AND 100),
    assessment_score INTEGER,
    enrolled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (subscription_id) REFERENCES lms_subscriptions(id) ON DELETE CASCADE,
    FOREIGN KEY (organisation_id) REFERENCES lms_organisations(id) ON DELETE SET NULL,
    UNIQUE (account_id, course_slug, course_version)
  )`,
  `CREATE TABLE IF NOT EXISTS lms_lesson_progress (
    id TEXT PRIMARY KEY,
    enrolment_id TEXT NOT NULL,
    module_id TEXT NOT NULL,
    lesson_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    selected_answer INTEGER,
    knowledge_check_passed INTEGER NOT NULL DEFAULT 0 CHECK (knowledge_check_passed IN (0, 1)),
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enrolment_id) REFERENCES lms_enrolments(id) ON DELETE CASCADE,
    UNIQUE (enrolment_id, lesson_id)
  )`,
  `CREATE TABLE IF NOT EXISTS lms_assessment_attempts (
    id TEXT PRIMARY KEY,
    enrolment_id TEXT NOT NULL,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    score_percent INTEGER NOT NULL CHECK (score_percent BETWEEN 0 AND 100),
    pass_mark INTEGER NOT NULL CHECK (pass_mark BETWEEN 1 AND 100),
    passed INTEGER NOT NULL CHECK (passed IN (0, 1)),
    answers_json TEXT NOT NULL,
    started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enrolment_id) REFERENCES lms_enrolments(id) ON DELETE CASCADE,
    UNIQUE (enrolment_id, attempt_number)
  )`,
  `CREATE TABLE IF NOT EXISTS lms_certificates (
    id TEXT PRIMARY KEY,
    enrolment_id TEXT NOT NULL UNIQUE,
    account_id TEXT NOT NULL,
    certificate_number TEXT NOT NULL UNIQUE,
    verification_token TEXT NOT NULL UNIQUE,
    course_slug TEXT NOT NULL,
    course_code TEXT NOT NULL,
    course_title TEXT NOT NULL,
    course_version TEXT NOT NULL,
    learner_name TEXT NOT NULL,
    score_percent INTEGER NOT NULL CHECK (score_percent BETWEEN 0 AND 100),
    statement TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'valid' CHECK (status IN ('valid', 'withdrawn', 'superseded')),
    issued_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    withdrawn_at TEXT,
    withdrawal_reason TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (enrolment_id) REFERENCES lms_enrolments(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS lms_audit_logs (
    id TEXT PRIMARY KEY,
    account_id TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    ip_address TEXT,
    user_agent TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES customer_accounts(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS webhook_events (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    external_event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    processing_status TEXT NOT NULL DEFAULT 'received',
    error_message TEXT,
    received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TEXT,
    UNIQUE (source, external_event_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_lms_subscriptions_account ON lms_subscriptions(account_id, status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_subscriptions_stripe_customer ON lms_subscriptions(stripe_customer_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_members_organisation ON lms_organisation_members(organisation_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_members_account ON lms_organisation_members(account_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_members_invited_email ON lms_organisation_members(invited_email, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_enrolments_account ON lms_enrolments(account_id, status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_enrolments_subscription ON lms_enrolments(subscription_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_progress_enrolment ON lms_lesson_progress(enrolment_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_assessments_enrolment ON lms_assessment_attempts(enrolment_id, attempt_number)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_certificates_account ON lms_certificates(account_id, issued_at)`,
  `CREATE INDEX IF NOT EXISTS idx_lms_audit_entity ON lms_audit_logs(entity_type, entity_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_events_source ON webhook_events(source, processing_status)`,
] as const;
