import { assessmentQuestion, lesson, type LibraryCourse } from './libraryCourseTypes';

const allPlans = ['Learner', 'Learner Plus', 'Team 5', 'Team 15'] as const;

export const coreLibraryCourses: LibraryCourse[] = [
  {
    code: 'SME-BUS-101',
    slug: 'starting-a-small-business',
    title: 'Starting a Small Business',
    category: 'Business and enterprise',
    shortDescription: 'Turn an idea into a focused, testable and financially sensible small business.',
    overview: 'This practical foundation course guides learners from an early idea through customer discovery, a simple business model, pricing, cash planning and a controlled launch. It is designed to help learners make evidence-led decisions before committing significant time or money.',
    audience: ['People considering self-employment', 'New sole traders and small-company founders', 'Team members supporting a new business project'],
    prerequisites: 'No previous business experience is required. Learners should have a business idea or a problem they may want to solve.',
    level: 'Foundation', featured: true, version: '1.0', reviewDate: 'August 2027',
    includedPlans: [...allPlans],
    learningOutcomes: [
      'Describe a clear customer problem and useful business outcome.',
      'Use low-cost tests to gather evidence of demand.',
      'Explain the main parts of a simple business model.',
      'Calculate basic price, cost and contribution figures.',
      'Prepare a practical ninety-day launch plan with measurable checkpoints.',
    ],
    modules: [
      {
        id: 'idea', title: 'Module 1: From idea to useful proposition',
        description: 'Define the customer, the problem and the outcome before building the service.',
        lessons: [
          lesson('customer-problem', 'Define the customer problem', 'Move from a broad idea to a specific problem worth solving.', 12,
            ['Identify a defined customer group.', 'Separate symptoms from the underlying problem.', 'Write a simple problem statement.'],
            [
              { heading: 'Start with the situation, not the product', paragraphs: ['A business is stronger when it begins with a real customer situation rather than a product the founder happens to like. Describe who experiences the problem, when it occurs, what they currently do and why the current approach is unsatisfactory.'] },
              { heading: 'A useful problem statement', bullets: ['Names a specific customer group.', 'Describes an observable problem or unmet need.', 'Explains the practical consequence of leaving it unresolved.', 'Avoids assuming that your preferred solution is the only answer.'], callout: 'A problem can be genuine without being commercially important. The customer must care enough to change behaviour, time or spending.' },
            ],
            { question: 'Which statement is the best starting point for a business idea?', options: ['Everyone needs my app', 'Independent cafés lose time reconciling delivery-platform orders each week', 'My logo looks professional'], answer: 1, explanation: 'It identifies a customer group, a recurring problem and a practical consequence.' },
            { title: 'Problem interview preparation', instructions: ['Write five questions about the customer’s current behaviour.', 'Remove questions that invite a simple yes or no.', 'Include one question about what the problem currently costs in time, money or frustration.'] }),
          lesson('value-proposition', 'Create a clear value proposition', 'Explain the outcome your offer creates and why it is useful.', 12,
            ['Describe the customer outcome.', 'Distinguish features from benefits.', 'Draft a concise proposition.'],
            [
              { heading: 'Outcome before features', paragraphs: ['Features describe what a product or service contains. Benefits describe what changes for the customer. A useful proposition connects the customer, the problem, the result and the reason your approach is credible.'] },
              { heading: 'A practical formula', bullets: ['For: the defined customer.', 'Who need: the problem or job to be done.', 'Our service: the category of solution.', 'Helps them: the useful outcome.', 'By: the most important differentiator or method.'], callout: 'Avoid vague claims such as “high quality” unless you can explain how the customer will recognise or measure that quality.' },
            ],
            { question: 'Which is a benefit rather than a feature?', options: ['A dashboard with six tabs', 'Weekly reports are emailed automatically', 'The owner spends less time preparing the weekly report'], answer: 2, explanation: 'The third option describes the useful customer outcome.' }),
        ],
      },
      {
        id: 'evidence', title: 'Module 2: Test demand and design the model',
        description: 'Gather evidence, choose a workable route to market and define how the business creates value.',
        lessons: [
          lesson('test-demand', 'Test demand before building', 'Use controlled experiments to learn what customers will actually do.', 14,
            ['Choose an appropriate demand test.', 'Distinguish opinions from commitment.', 'Define a success measure before testing.'],
            [
              { heading: 'Evidence has different strengths', paragraphs: ['A compliment is weak evidence because it costs the customer nothing. Stronger evidence includes sharing contact details, booking a call, joining a waiting list, agreeing to a pilot or paying for a small trial.'] },
              { heading: 'Design a useful test', bullets: ['State the assumption being tested.', 'Choose the smallest credible experiment.', 'Set a timeframe and success threshold.', 'Record objections and unexpected behaviour.', 'Decide in advance what would cause you to change direction.'], callout: 'Do not change the success measure after seeing the result. That makes the experiment harder to learn from.' },
            ],
            { question: 'Which is the strongest evidence of early demand?', options: ['A friend says the idea sounds good', 'A potential customer pays for a limited pilot', 'A social-media post receives views'], answer: 1, explanation: 'Payment for a pilot demonstrates commitment and a willingness to exchange value.' }),
          lesson('business-model', 'Build a simple business model', 'Connect customers, delivery, costs, revenue and key risks.', 14,
            ['Identify the main model components.', 'Recognise operational dependencies.', 'Describe how revenue and costs interact.'],
            [
              { heading: 'The model must work as a system', paragraphs: ['A good offer can still fail if it is expensive to deliver, difficult to reach customers or dependent on a fragile supplier. Map how the business attracts customers, delivers the outcome, receives payment and supports the customer afterwards.'] },
              { heading: 'Minimum model questions', bullets: ['Who buys, uses and influences the purchase?', 'How will customers discover and evaluate the offer?', 'What must happen to deliver the service consistently?', 'Which costs increase with each sale?', 'Which resources, suppliers or permissions are essential?', 'What could stop the model working at the expected scale?'] },
            ],
            { question: 'Why should a founder map operational dependencies?', options: ['To make the plan longer', 'To identify resources or suppliers that could prevent reliable delivery', 'To avoid speaking to customers'], answer: 1, explanation: 'Dependencies reveal practical risks that may affect delivery, cost or continuity.' }),
        ],
      },
      {
        id: 'launch', title: 'Module 3: Price, plan and launch',
        description: 'Set a sustainable starting price and turn the work into a controlled launch plan.',
        lessons: [
          lesson('pricing-cash', 'Pricing, costs and cash flow', 'Understand the minimum financial information needed before launch.', 16,
            ['Separate fixed and variable costs.', 'Estimate contribution per sale.', 'Explain why profit and cash are different.'],
            [
              { heading: 'Know what each sale contributes', paragraphs: ['Variable costs rise when you make a sale. Fixed costs usually continue regardless of sales volume. The selling price minus the direct variable cost gives a basic contribution towards overheads, taxes, risk and profit.'] },
              { heading: 'Cash timing matters', bullets: ['A sale may be recorded before the customer pays.', 'Suppliers, tax and subscriptions may be due before cash arrives.', 'Refunds and chargebacks can reverse expected cash.', 'A reserve provides time to respond to delays or lower-than-expected sales.'], callout: 'A price should reflect customer value and market conditions, but it must also support safe and reliable delivery.' },
            ],
            { question: 'Why can a profitable business still run out of cash?', options: ['Profit and cash always arrive at the same time', 'Payments may be received after costs become due', 'Fixed costs disappear when sales increase'], answer: 1, explanation: 'Timing differences can create a cash shortage even when the accounts show a profit.' }),
          lesson('ninety-day-plan', 'Create a ninety-day launch plan', 'Turn assumptions into actions, owners and measurable checkpoints.', 12,
            ['Set launch priorities.', 'Choose measurable indicators.', 'Schedule review decisions.'],
            [
              { heading: 'Work in short evidence cycles', paragraphs: ['A launch plan should not pretend that every assumption is already true. The first ninety days should focus on validating demand, delivering consistently, learning from customers and protecting cash.'] },
              { heading: 'Include four types of action', bullets: ['Customer actions: interviews, demonstrations, proposals and follow-up.', 'Delivery actions: processes, suppliers, quality checks and support.', 'Financial actions: prices, invoices, reserves and weekly cash review.', 'Governance actions: records, contracts, privacy, safety and relevant permissions.'], callout: 'Give each action an owner, deadline and definition of done. Review the plan weekly and record material changes.' },
            ],
            { question: 'What makes a launch action accountable?', options: ['It sounds ambitious', 'It has an owner, deadline and clear definition of done', 'It appears on several lists'], answer: 1, explanation: 'Ownership, timing and completion criteria make progress visible and reviewable.' }),
        ],
      },
    ],
    finalAssessment: {
      title: 'Starting a Small Business final assessment',
      instructions: 'Answer all six questions. A score of 80% or higher is required. You may review the course and attempt the assessment again.',
      passMark: 80,
      questions: [
        assessmentQuestion('q1', 'What should be defined before selecting a solution?', ['The customer problem', 'The company colour palette', 'The final office location'], 0, 'A useful business starts with a defined customer problem.'),
        assessmentQuestion('q2', 'Which demand signal involves the greatest customer commitment?', ['A like', 'A compliment', 'Payment for a trial'], 2, 'Payment is stronger evidence than an opinion or passive reaction.'),
        assessmentQuestion('q3', 'What does contribution per sale help fund?', ['Only direct variable costs', 'Overheads, risk, tax and profit after variable costs', 'Only the founder’s salary'], 1, 'Contribution is what remains after the direct variable cost.'),
        assessmentQuestion('q4', 'Why is cash-flow planning necessary?', ['Because profit and available cash may arise at different times', 'Because businesses should never invoice customers', 'Because fixed costs are always zero'], 0, 'Cash timing may differ from accounting profit.'),
        assessmentQuestion('q5', 'Which launch measure is most useful?', ['A measure connected to an important assumption or objective', 'The number of colours on the website', 'A measure selected after the result is known'], 0, 'Measures should support a defined decision.'),
        assessmentQuestion('q6', 'What should a ninety-day action include?', ['An owner and completion criteria', 'Only a motivational title', 'No deadline'], 0, 'Accountable actions need ownership, timing and a definition of done.'),
      ],
    },
    certificateStatement: 'Certificate of completion: Starting a Small Business (foundation awareness course).',
    importantNotice: 'This course provides general educational information. It is not legal, tax, accounting, investment or regulated business advice.',
  },
  {
    code: 'SME-AI-101', slug: 'ai-literacy-for-everyday-work', title: 'AI Literacy for Everyday Work',
    category: 'Digital skills and AI',
    shortDescription: 'Use generative AI productively while checking accuracy, privacy, ownership and risk.',
    overview: 'This course gives non-technical learners a practical framework for using generative AI at work. It covers appropriate tasks, prompt design, verification, confidential information, bias, accountability and a repeatable human-review process.',
    audience: ['Employees and managers using generative AI', 'Small-business owners', 'People responsible for reviewing AI-assisted work'],
    prerequisites: 'No technical knowledge is required. Access to an approved generative AI service is helpful but not necessary.',
    level: 'Foundation', featured: true, version: '1.0', reviewDate: 'February 2027', includedPlans: [...allPlans],
    learningOutcomes: ['Explain what generative AI can and cannot reliably do.', 'Select appropriate low-risk tasks.', 'Write clearer prompts.', 'Verify important outputs.', 'Protect confidential and personal information.', 'Keep human accountability for decisions.'],
    modules: [
      { id: 'understand', title: 'Module 1: Understand the tool', description: 'Build an accurate mental model of generative AI and its limitations.', lessons: [
        lesson('capabilities', 'Capabilities and limitations', 'Understand why fluent output is not the same as verified truth.', 12,
          ['Describe common generative tasks.', 'Recognise hallucination and uncertainty.', 'Choose suitable uses.'],
          [
            { heading: 'What the system is doing', paragraphs: ['Generative AI produces new text, images or other content by modelling patterns. It can be useful for drafting, reorganising, comparing, brainstorming and transforming information. It does not possess guaranteed knowledge of the facts relevant to your task.'] },
            { heading: 'Use task risk to decide the level of review', bullets: ['Low-risk: brainstorming headings or changing tone.', 'Medium-risk: drafting customer information or internal guidance.', 'High-risk: legal, medical, financial, safeguarding, employment, security or safety decisions.'], callout: 'The more serious the consequence of an error, the stronger the human review and source verification must be.' },
          ],
          { question: 'Why can a polished AI answer still be unsafe?', options: ['Fluency does not prove factual accuracy', 'Long answers are always wrong', 'AI cannot create text'], answer: 0, explanation: 'Generative systems can produce plausible but incorrect content.' }),
        lesson('task-selection', 'Select appropriate tasks', 'Decide what to automate, assist or keep fully human-led.', 11,
          ['Assess consequence and sensitivity.', 'Identify required human judgement.', 'Set a clear permitted purpose.'],
          [
            { heading: 'Three useful categories', bullets: ['Automate: repetitive low-risk transformation with clear checking.', 'Assist: the system drafts or analyses, while a person verifies and decides.', 'Human-led: sensitive or high-consequence work where judgement, empathy or authority is central.'] },
            { heading: 'Ask before using AI', bullets: ['Is the information permitted to be entered?', 'Could an error harm a person or create a legal or operational problem?', 'Can the output be checked against reliable evidence?', 'Who remains responsible for the decision?'] },
          ],
          { question: 'Which task is most suitable for AI assistance rather than autonomous decision-making?', options: ['Making a final safeguarding decision', 'Drafting headings for a reviewed internal guide', 'Authorising a financial payment'], answer: 1, explanation: 'Drafting headings is low risk and can be checked easily.' }),
      ] },
      { id: 'prompt', title: 'Module 2: Prompt and review', description: 'Give clear instructions and use a disciplined review process.', lessons: [
        lesson('prompt-design', 'Write effective prompts', 'Provide purpose, context, constraints and output requirements.', 13,
          ['Use a repeatable prompt structure.', 'Supply relevant context without protected information.', 'Request transparent output.'],
          [
            { heading: 'A reliable prompt structure', bullets: ['Goal: what outcome is required?', 'Context: what background is genuinely relevant?', 'Audience: who will use the output?', 'Constraints: length, tone, exclusions and policy rules.', 'Format: table, headings, checklist or draft.', 'Checking: ask the system to identify assumptions and uncertainty.'] },
            { heading: 'Iterate deliberately', paragraphs: ['Large tasks are easier to check when divided into stages. Ask for an outline, review it, then request one section at a time. Correct the source information rather than repeatedly asking the system to “try again” without explaining the problem.'] },
          ],
          { question: 'Which prompt element helps the system tailor the result to the reader?', options: ['Audience', 'Browser history', 'Screen brightness'], answer: 0, explanation: 'Naming the audience helps shape language, detail and format.' },
          { title: 'Prompt improvement', instructions: ['Choose a vague prompt you have used before.', 'Add a goal, audience, constraints and required format.', 'List the facts that still need independent verification.'] }),
        lesson('verification', 'Verify and improve outputs', 'Check facts, reasoning, completeness, tone and unintended risk.', 14,
          ['Use primary or authoritative sources.', 'Check calculations and cited material.', 'Record material human changes.'],
          [
            { heading: 'Review in layers', bullets: ['Accuracy: are factual claims supported?', 'Completeness: is important context missing?', 'Reasoning: does the conclusion follow from the evidence?', 'Safety: could the advice cause harm?', 'Fairness: does the output rely on stereotypes or irrelevant assumptions?', 'Presentation: is the tone appropriate and accessible?'] },
            { heading: 'Do not verify AI with AI alone', paragraphs: ['A second generated answer may repeat the same weakness. Important claims should be checked against reliable records, official guidance, direct evidence or a qualified person.'] },
          ],
          { question: 'What is the strongest way to verify an important factual claim?', options: ['Ask the same AI again', 'Check an authoritative source or direct record', 'Assume confidence means accuracy'], answer: 1, explanation: 'Independent evidence is required for important claims.' }),
      ] },
      { id: 'responsibility', title: 'Module 3: Use AI responsibly', description: 'Protect information, reduce bias and retain accountable human control.', lessons: [
        lesson('privacy-security', 'Privacy, confidentiality and security', 'Avoid exposing protected information through prompts or outputs.', 13,
          ['Recognise sensitive inputs.', 'Use approved tools and policies.', 'Reduce prompt and output exposure.'],
          [
            { heading: 'Information should be classified before use', bullets: ['Public information may be suitable for approved public tools.', 'Internal information may require an organisation-controlled service.', 'Personal, confidential, commercially sensitive or security information needs explicit authority and safeguards.', 'Passwords, authentication secrets and payment-card details should not be entered.'] },
            { heading: 'Minimise what the tool receives', paragraphs: ['Use fictional examples, remove identifiers and provide only the information needed for the task. Check whether the service retains prompts, uses them for training or permits administrative control.'] },
          ],
          { question: 'What is the safest default for confidential information?', options: ['Enter it into any free tool', 'Use it only through an approved service and permitted process', 'Post it publicly first'], answer: 1, explanation: 'Confidential information requires approved systems and controls.' }),
        lesson('bias-accountability', 'Bias, fairness and human accountability', 'Challenge assumptions and make decision ownership visible.', 14,
          ['Recognise possible bias.', 'Avoid proxy discrimination.', 'Document human review and decisions.'],
          [
            { heading: 'Bias can enter at several points', bullets: ['Training data may reflect past inequality.', 'The prompt may contain assumptions.', 'The output may omit minority experiences.', 'A reviewer may accept a preferred answer without challenge.'] },
            { heading: 'Keep responsibility with a named person', paragraphs: ['An organisation should be able to explain who approved the use, who reviewed the output and who made the decision. “The AI said so” is not a defensible governance process.'] },
            { heading: 'A simple responsible-use record', bullets: ['Purpose and tool used.', 'Information entered.', 'Checks completed and sources consulted.', 'Material changes made by the reviewer.', 'Final decision-maker.'] },
          ],
          { question: 'Who should remain responsible for an important decision?', options: ['A named authorised human decision-maker', 'The software alone', 'Nobody if AI was used'], answer: 0, explanation: 'Accountability cannot be transferred to a tool.' }),
      ] },
    ],
    finalAssessment: { title: 'AI Literacy final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What does fluent AI output demonstrate?', ['Guaranteed truth', 'Clear presentation only, not guaranteed accuracy', 'Legal approval'], 1, 'Fluency is not evidence of truth.'),
      assessmentQuestion('q2', 'Which task needs the strongest human control?', ['Changing a heading', 'Making a safeguarding decision', 'Generating three slogan ideas'], 1, 'Safeguarding decisions have serious consequences.'),
      assessmentQuestion('q3', 'What should a strong prompt include?', ['Goal, context, audience and constraints', 'Only one vague sentence', 'A password'], 0, 'Clear task information improves usefulness and reviewability.'),
      assessmentQuestion('q4', 'How should an important claim be checked?', ['Against authoritative evidence', 'By asking for a more confident answer', 'It does not need checking'], 0, 'Important facts need independent verification.'),
      assessmentQuestion('q5', 'When may confidential information be used?', ['Whenever a tool is free', 'Only through an approved and permitted process', 'Whenever the answer will be short'], 1, 'Confidential information requires controlled use.'),
      assessmentQuestion('q6', 'What is a proper AI governance record?', ['The tool name only', 'Purpose, information, checks and decision-maker', 'No record'], 1, 'The record should show how the output was used and reviewed.'),
    ] },
    certificateStatement: 'Certificate of completion: AI Literacy for Everyday Work.',
    importantNotice: 'This course supports general AI awareness. It does not approve any particular tool or replace an organisation’s information-security, data-protection or professional decision-making requirements.',
  },
  {
    code: 'SME-CUS-101', slug: 'customer-service-essentials', title: 'Customer Service Essentials', category: 'Workplace essentials',
    shortDescription: 'Handle enquiries, complaints and difficult conversations with clarity, fairness and accountability.',
    overview: 'A practical service course covering active listening, accurate records, expectation setting, complaint investigation, de-escalation and service recovery. Learners practise separating emotion from the issue while preserving dignity and clear boundaries.',
    audience: ['Customer-service staff', 'Small-business owners', 'Operational managers', 'People handling complaints or support requests'],
    prerequisites: 'No previous customer-service training is required.', level: 'Foundation', featured: true, version: '1.0', reviewDate: 'August 2027', includedPlans: [...allPlans],
    learningOutcomes: ['Identify the customer’s underlying need.', 'Set realistic expectations.', 'Record facts accurately.', 'Use a fair complaint process.', 'De-escalate tension safely.', 'Confirm actions and close the loop.'],
    modules: [
      { id: 'understand', title: 'Module 1: Understand and communicate', description: 'Listen for the need and create a clear shared understanding.', lessons: [
        lesson('active-listening', 'Active listening and clarification', 'Gather facts without interrupting, assuming or becoming defensive.', 12,
          ['Use open and closed questions appropriately.', 'Reflect back the issue.', 'Separate facts, feelings and desired outcome.'],
          [
            { heading: 'Listen for three layers', bullets: ['What happened: the observable facts.', 'What it meant to the customer: impact and emotion.', 'What outcome is being requested: action, explanation, correction or reassurance.'] },
            { heading: 'Clarify without interrogating', paragraphs: ['Explain why a question is needed, ask one point at a time and summarise what you have understood. Avoid blaming language such as “Why did you not…?” when a neutral question would gather the same information.'] },
          ],
          { question: 'What should you confirm before offering a solution?', options: ['The facts and the outcome the customer is seeking', 'Only the customer’s postcode', 'That the customer agrees with you'], answer: 0, explanation: 'A solution should respond to the actual issue and requested outcome.' }),
        lesson('expectations', 'Set clear expectations', 'Explain ownership, timescales, limits and next steps.', 11,
          ['Avoid unsupported promises.', 'Explain what will happen next.', 'Use plain language.'],
          [
            { heading: 'Promise the process you can control', paragraphs: ['Do not guarantee an outcome before investigation or outside your authority. You can usually confirm who owns the next action, what information is needed, when an update is due and how the customer will be contacted.'] },
            { heading: 'A complete expectation includes', bullets: ['The next action.', 'The person or team responsible.', 'A realistic timeframe.', 'Any information the customer must provide.', 'What happens if the timeframe changes.'] },
          ],
          { question: 'Which promise is appropriate before an investigation?', options: ['We will definitely refund you', 'I will review the record and update you by 4 pm tomorrow', 'The supplier is certainly at fault'], answer: 1, explanation: 'It commits to a controllable process and update.' }),
      ] },
      { id: 'resolve', title: 'Module 2: Resolve complaints fairly', description: 'Use evidence, authority and clear reasoning to reach a proportionate outcome.', lessons: [
        lesson('complaint-process', 'A structured complaint process', 'Acknowledge, clarify, investigate, decide and confirm.', 14,
          ['Apply a consistent workflow.', 'Preserve evidence.', 'Explain the decision.'],
          [
            { heading: 'Five stages', bullets: ['Acknowledge the concern and its impact.', 'Clarify the issues, requested outcome and scope.', 'Investigate records, policies and relevant accounts.', 'Decide within authority or escalate to the correct person.', 'Confirm the outcome, reasons, remedy and review route.'] },
            { heading: 'Keep an objective record', paragraphs: ['Record dates, communications, evidence considered, actions and reasons. Distinguish what the customer said from what the organisation has independently confirmed.'] },
          ],
          { question: 'What should a complaint record distinguish?', options: ['Allegations from independently confirmed facts', 'Customers from staff by writing style', 'Short calls from long calls only'], answer: 0, explanation: 'The record should make the evidential status of information clear.' }),
        lesson('service-recovery', 'Service recovery and remedies', 'Match the remedy to the failure and customer impact.', 12,
          ['Identify the service failure.', 'Choose a proportionate remedy.', 'Prevent recurrence.'],
          [
            { heading: 'A remedy should do useful work', bullets: ['Correct the practical problem where possible.', 'Acknowledge avoidable inconvenience or distress.', 'Restore the customer to the expected position where appropriate.', 'Explain any limit to what can be offered.', 'Feed lessons back into process improvement.'] },
            { heading: 'Do not use goodwill to hide a control failure', paragraphs: ['A voucher or apology may help the relationship, but the underlying issue may still require a process change, staff briefing, supplier escalation or system correction.'] },
          ],
          { question: 'What should happen after resolving a repeated service failure?', options: ['Ignore the cause', 'Consider a process or control improvement', 'Delete the complaint'], answer: 1, explanation: 'Service recovery should include learning and prevention.' }),
      ] },
      { id: 'difficult', title: 'Module 3: Difficult conversations', description: 'Reduce tension, preserve boundaries and protect safety.', lessons: [
        lesson('de-escalation', 'De-escalate tension', 'Respond calmly without dismissing the customer’s concern.', 14,
          ['Use calm and specific language.', 'Recognise escalation triggers.', 'Offer controlled choices.'],
          [
            { heading: 'Regulate the interaction', bullets: ['Slow your pace and lower unnecessary volume.', 'Acknowledge the impact without admitting facts not established.', 'Use the customer’s main issue in your summary.', 'Offer two realistic next steps where possible.', 'Avoid matching sarcasm, aggression or threats.'] },
            { heading: 'Separate emotion from action', paragraphs: ['A customer can be angry and still have a valid issue. Focus on the action that can be taken while recognising the emotion in neutral language.'] },
          ],
          { question: 'Which response is most likely to de-escalate?', options: ['Calmly summarising the issue and offering the available next steps', 'Speaking more loudly', 'Telling the customer to calm down'], answer: 0, explanation: 'A clear summary and controlled options restore structure.' }),
        lesson('boundaries', 'Set boundaries and escalate safely', 'Respond to abusive, discriminatory or threatening conduct.', 12,
          ['State behavioural boundaries.', 'Know when to end or transfer contact.', 'Preserve safety and evidence.'],
          [
            { heading: 'Respect is a two-way requirement', paragraphs: ['Staff should not be expected to accept threats, discriminatory abuse or conduct that prevents the service from continuing. State the specific behaviour that must stop and the consequence if it continues.'] },
            { heading: 'Escalate when', bullets: ['There is an immediate safety concern.', 'The customer threatens harm or criminal conduct.', 'The issue exceeds your authority.', 'A vulnerability or safeguarding concern requires specialist action.', 'The conversation cannot continue productively after a clear warning.'] },
          ],
          { question: 'What should a boundary statement identify?', options: ['The specific unacceptable behaviour and what will happen if it continues', 'The employee’s private opinion', 'A guaranteed ban in every case'], answer: 0, explanation: 'Specific, proportionate boundaries are clearer and fairer.' }),
      ] },
    ],
    finalAssessment: { title: 'Customer Service Essentials final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What are the three layers to listen for?', ['Facts, impact and requested outcome', 'Price, postcode and age', 'Only emotion'], 0, 'A complete understanding includes facts, impact and desired outcome.'),
      assessmentQuestion('q2', 'What can usually be promised before investigation?', ['A definite refund', 'A process, owner and update time', 'That another person is at fault'], 1, 'Promise only what is within control.'),
      assessmentQuestion('q3', 'Which stage follows clarification?', ['Investigation', 'Deletion', 'Advertising'], 0, 'Relevant evidence should be investigated before a decision.'),
      assessmentQuestion('q4', 'What makes a remedy proportionate?', ['It responds to the actual failure and impact', 'It is always the most expensive option', 'It avoids explaining the decision'], 0, 'The remedy should match the failure and consequences.'),
      assessmentQuestion('q5', 'Which technique supports de-escalation?', ['Matching the customer’s aggression', 'Summarising and offering realistic choices', 'Interrupting repeatedly'], 1, 'Structure and calm choices reduce escalation.'),
      assessmentQuestion('q6', 'When may contact need to end?', ['When abusive or threatening behaviour continues after a clear boundary', 'Whenever the customer asks a question', 'Whenever a complaint is made'], 0, 'Safety and workable communication must be protected.'),
    ] },
    certificateStatement: 'Certificate of completion: Customer Service Essentials.',
    importantNotice: 'This course provides general service skills. Organisation-specific complaints, vulnerability, safeguarding, emergency and legal escalation procedures must still be followed.',
  },
  {
    code: 'SME-COM-101', slug: 'communication-at-work', title: 'Communication at Work', category: 'Workplace essentials',
    shortDescription: 'Write and speak with clear purpose, appropriate tone and accountable actions.',
    overview: 'This course develops practical workplace communication across email, meetings, telephone calls and difficult messages. Learners practise structuring information, selecting the right channel, confirming decisions and producing records that other people can act on.',
    audience: ['Employees at any level', 'Managers and team leaders', 'People working with customers, suppliers or partners'], prerequisites: 'No prerequisites.',
    level: 'Foundation', featured: true, version: '1.0', reviewDate: 'August 2027', includedPlans: [...allPlans],
    learningOutcomes: ['State purpose and action clearly.', 'Choose an appropriate communication channel.', 'Adapt tone to audience and risk.', 'Structure meetings and written messages.', 'Confirm decisions, owners and deadlines.', 'Reduce ambiguity and avoidable conflict.'],
    modules: [
      { id: 'clear', title: 'Module 1: Clear messages', description: 'Make the purpose, context and action easy to find.', lessons: [
        lesson('purpose', 'Lead with purpose and action', 'Help the reader understand why the message exists.', 11,
          ['Write a clear opening.', 'Separate context from action.', 'Use informative headings.'],
          [
            { heading: 'The first lines should orient the reader', bullets: ['Reason for the message.', 'Decision, question or action required.', 'Deadline or urgency where relevant.', 'Where supporting detail can be found.'] },
            { heading: 'Use the BLUF principle when appropriate', paragraphs: ['Bottom line up front means placing the main decision or required action before background detail. It is useful for operational messages, approvals and updates, but sensitive communications may need a more considerate opening.'] },
          ],
          { question: 'What should be easy to identify near the beginning of an operational email?', options: ['The purpose and required action', 'Every historical detail', 'The sender’s favourite phrase'], answer: 0, explanation: 'Readers need to know why the message matters and what they must do.' }),
        lesson('plain-language', 'Use plain and precise language', 'Reduce jargon, ambiguity and unnecessary effort.', 11,
          ['Replace vague phrases.', 'Use specific dates and owners.', 'Write for the intended reader.'],
          [
            { heading: 'Precision prevents rework', bullets: ['Use “by 3 pm on 12 August” rather than “soon”.', 'Name the responsible person or role.', 'Define unfamiliar abbreviations.', 'Break complicated instructions into numbered steps.', 'Use active voice where responsibility matters.'] },
            { heading: 'Plain does not mean simplistic', paragraphs: ['Plain language preserves the necessary meaning while reducing unnecessary complexity. Technical terms may be appropriate when the audience understands them and precision depends on them.'] },
          ],
          { question: 'Which phrase is most precise?', options: ['Please do this soon', 'Sam must submit the signed form by 3 pm on 12 August', 'Someone should look at it'], answer: 1, explanation: 'It identifies the owner, action and deadline.' }),
      ] },
      { id: 'channel', title: 'Module 2: Channel and tone', description: 'Match the method and tone to urgency, sensitivity and record needs.', lessons: [
        lesson('channel-choice', 'Choose the right channel', 'Balance speed, interaction, security and the need for a record.', 12,
          ['Assess channel suitability.', 'Protect sensitive information.', 'Use follow-up records.'],
          [
            { heading: 'Channel questions', bullets: ['Does the matter need immediate two-way discussion?', 'Is a durable record required?', 'Is the information sensitive or restricted?', 'Could tone be misunderstood in writing?', 'Who needs access to the decision afterwards?'] },
            { heading: 'Combine channels deliberately', paragraphs: ['A difficult issue may be discussed by telephone or video, then confirmed in writing. The written summary should record decisions and actions without creating a misleading transcript of every word.'] },
          ],
          { question: 'What is a sensible approach to a sensitive, complicated issue?', options: ['A discussion followed by a written summary', 'A public social-media comment', 'No record at all'], answer: 0, explanation: 'Discussion supports nuance while the summary preserves accountability.' }),
        lesson('tone', 'Use professional tone', 'Be clear, respectful and proportionate without becoming vague.', 12,
          ['Recognise tone risks.', 'Write firm but respectful boundaries.', 'Avoid accidental escalation.'],
          [
            { heading: 'Tone is created by choices', bullets: ['Opening and closing language.', 'Sentence length and punctuation.', 'Degree of certainty.', 'Use of blame, accusation or assumptions.', 'Whether the message acknowledges impact and next steps.'] },
            { heading: 'Firm is not rude', paragraphs: ['A professional boundary can be direct: identify the requirement, the reason and the consequence. Avoid sarcasm, threats or language designed to humiliate.'] },
          ],
          { question: 'Which message is firm and professional?', options: ['You clearly do not understand', 'The form must be received by Friday; otherwise the request cannot be processed', 'Whatever, send it when you can'], answer: 1, explanation: 'It states the requirement and consequence without personal criticism.' }),
      ] },
      { id: 'accountability', title: 'Module 3: Meetings and follow-through', description: 'Turn discussion into recorded decisions and completed actions.', lessons: [
        lesson('meetings', 'Run purposeful meetings', 'Use an agenda, decision points and clear roles.', 13,
          ['Define the meeting outcome.', 'Separate information, discussion and decision items.', 'Manage time and participation.'],
          [
            { heading: 'A meeting should earn its place', bullets: ['Purpose and required outcome.', 'People who need to contribute or decide.', 'Pre-reading and preparation.', 'Time allocated to each item.', 'Decision owner and follow-up method.'] },
            { heading: 'Close each item', paragraphs: ['Before moving on, state the decision, action owner, deadline and unresolved point. This prevents people leaving with different interpretations.'] },
          ],
          { question: 'What should happen before a meeting moves to the next item?', options: ['Confirm the decision or action', 'Delete the agenda', 'Invite more people automatically'], answer: 0, explanation: 'Closing the item creates a shared record of the outcome.' }),
        lesson('close-loop', 'Close the communication loop', 'Confirm receipt, decisions, actions and changes.', 11,
          ['Use action summaries.', 'Escalate blocked work.', 'Update people when plans change.'],
          [
            { heading: 'An action summary should contain', bullets: ['Action.', 'Owner.', 'Deadline.', 'Dependencies.', 'Status or evidence of completion.'] },
            { heading: 'Silence is not confirmation', paragraphs: ['Where the consequence matters, obtain explicit confirmation that the person has received and understood the action. If a deadline cannot be met, communicate early and propose a revised plan.'] },
          ],
          { question: 'What should happen when a deadline becomes unachievable?', options: ['Say nothing', 'Communicate early and agree a revised plan', 'Mark the task complete'], answer: 1, explanation: 'Early communication allows dependencies and expectations to be managed.' }),
      ] },
    ],
    finalAssessment: { title: 'Communication at Work final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What belongs near the start of an operational message?', ['Purpose and required action', 'All background history', 'An unrelated anecdote'], 0, 'Readers need orientation and action.'),
      assessmentQuestion('q2', 'Which deadline is clearest?', ['Soon', 'By 3 pm on 12 August', 'Whenever possible'], 1, 'Specific timing reduces ambiguity.'),
      assessmentQuestion('q3', 'What can follow a sensitive verbal discussion?', ['A concise written decision and action summary', 'No record', 'A public post'], 0, 'A written summary preserves accountability.'),
      assessmentQuestion('q4', 'What makes a boundary professional?', ['Clear requirement, reason and consequence', 'Sarcasm', 'Personal criticism'], 0, 'Professional boundaries focus on the requirement and process.'),
      assessmentQuestion('q5', 'What should close a meeting item?', ['A confirmed decision or action', 'A new unrelated topic', 'Silence'], 0, 'Closure prevents different interpretations.'),
      assessmentQuestion('q6', 'What should an action record include?', ['Owner and deadline', 'Only the meeting date', 'No status'], 0, 'Ownership and timing are essential.'),
    ] },
    certificateStatement: 'Certificate of completion: Communication at Work.',
    importantNotice: 'Learners must also follow organisation-specific confidentiality, records-management, accessibility and approved-channel requirements.',
  },
  {
    code: 'SME-PRO-101', slug: 'time-management-and-personal-productivity', title: 'Time Management and Personal Productivity', category: 'Personal development',
    shortDescription: 'Build a realistic system for commitments, priorities, focused work and weekly review.',
    overview: 'This course replaces unrealistic “do more” advice with a practical operating system. Learners capture commitments, distinguish actions from projects, prioritise by consequence, protect focused work, manage interruptions and review their workload honestly.',
    audience: ['Busy employees and managers', 'Small-business owners', 'People managing competing deadlines'], prerequisites: 'No prerequisites.',
    level: 'Foundation', featured: true, version: '1.0', reviewDate: 'August 2027', includedPlans: [...allPlans],
    learningOutcomes: ['Use one trusted capture system.', 'Convert vague work into defined actions.', 'Prioritise by consequence and dependency.', 'Plan capacity realistically.', 'Protect focused work.', 'Conduct a weekly review.'],
    modules: [
      { id: 'system', title: 'Module 1: Build a trusted system', description: 'Get commitments out of memory and into a usable structure.', lessons: [
        lesson('capture', 'Capture commitments reliably', 'Use one trusted place for actions and follow-up.', 11,
          ['Reduce scattered reminders.', 'Separate tasks, appointments and reference.', 'Create a capture habit.'],
          [
            { heading: 'Memory is for thinking, not storage', paragraphs: ['When commitments are spread across messages, scraps of paper and memory, the person spends energy repeatedly trying to remember them. Capture everything into a trusted intake point, then process it at defined times.'] },
            { heading: 'Classify each item', bullets: ['Action: a specific physical or digital step.', 'Project: an outcome needing more than one action.', 'Appointment: work tied to a date and time.', 'Waiting for: an action owned by another person.', 'Reference: useful information with no current action.'] },
          ],
          { question: 'What is a project in a productivity system?', options: ['An outcome requiring more than one action', 'Any email', 'A completed appointment'], answer: 0, explanation: 'Projects need several actions and should not be treated as one vague task.' }),
        lesson('next-actions', 'Define the next action', 'Turn vague intentions into visible, achievable steps.', 11,
          ['Use action verbs.', 'Identify required context.', 'Reduce starting friction.'],
          [
            { heading: 'Vague work creates avoidance', bullets: ['“Budget” becomes “Download July transactions”.', '“Website” becomes “Draft the services-page headings”.', '“Speak to supplier” becomes “Email Priya requesting the revised delivery date”.'] },
            { heading: 'Make starting easy', paragraphs: ['A good next action is small enough to begin, specific enough to know when it is complete and connected to the desired outcome.'] },
          ],
          { question: 'Which is the clearest next action?', options: ['Marketing', 'Email the designer requesting the final banner by Friday', 'Think about things'], answer: 1, explanation: 'It contains a specific action, recipient and required result.' }),
      ] },
      { id: 'priority', title: 'Module 2: Decide what matters', description: 'Prioritise using consequence, timing, responsibility and dependencies.', lessons: [
        lesson('prioritise', 'Prioritise by consequence', 'Avoid treating every request as equally important.', 13,
          ['Assess impact and deadline.', 'Recognise dependencies.', 'Make trade-offs visible.'],
          [
            { heading: 'Use four questions', bullets: ['What happens if this is not done?', 'Is the deadline genuine and externally fixed?', 'Who or what is blocked by this action?', 'Does the action support an important responsibility or objective?'] },
            { heading: 'Urgency can be manufactured', paragraphs: ['A loud or recent request may feel urgent without having serious consequences. Compare it against legal, safety, customer, financial and dependency risks rather than reacting only to pressure.'] },
          ],
          { question: 'Which factor is most useful when comparing priorities?', options: ['The consequence of delay', 'The colour of the task label', 'Who sent the most emojis'], answer: 0, explanation: 'Consequence and dependency help identify material priority.' }),
        lesson('capacity', 'Plan realistic capacity', 'Leave room for administration, interruptions and recovery.', 13,
          ['Estimate available time.', 'Use buffers.', 'Limit work in progress.'],
          [
            { heading: 'A calendar is not fully available time', bullets: ['Meetings require preparation and follow-up.', 'Communication and administration consume capacity.', 'Travel and switching tasks take time.', 'Unexpected issues will occur.', 'Breaks support sustained attention and safer decisions.'] },
            { heading: 'Plan less, finish more', paragraphs: ['Choose a small number of meaningful outcomes for the day or week. Starting many tasks can create the appearance of activity while delaying completion.'] },
          ],
          { question: 'Why should a weekly plan contain buffer time?', options: ['To absorb normal interruptions and follow-up', 'To avoid all work', 'Because deadlines are optional'], answer: 0, explanation: 'Realistic plans account for predictable uncertainty.' }),
      ] },
      { id: 'focus', title: 'Module 3: Focus and review', description: 'Protect concentrated work and keep the system current.', lessons: [
        lesson('focus-blocks', 'Protect focused work', 'Reduce preventable interruption and task switching.', 12,
          ['Create a focus block.', 'Set communication expectations.', 'Use an interruption capture method.'],
          [
            { heading: 'Design the environment', bullets: ['Choose one defined outcome.', 'Close unrelated tabs and notifications.', 'Make required materials available first.', 'Set a finish time and short break.', 'Capture unrelated thoughts without changing task.'] },
            { heading: 'Availability should be intentional', paragraphs: ['Not every role can be unavailable for long periods. Agree response expectations and create shorter focus windows that respect operational responsibilities.'] },
          ],
          { question: 'What should a focus block begin with?', options: ['One defined outcome', 'Every task at once', 'Unrelated notifications'], answer: 0, explanation: 'A defined outcome directs attention and provides completion criteria.' }),
        lesson('weekly-review', 'Run a weekly review', 'Reset commitments, deadlines and priorities before the next week.', 13,
          ['Review every active project.', 'Update waiting items.', 'Plan the next week.'],
          [
            { heading: 'A weekly review includes', bullets: ['Empty capture points.', 'Review calendar history and upcoming dates.', 'Check each project has a next action.', 'Follow up waiting items.', 'Review risks, deadlines and capacity.', 'Choose the next week’s main outcomes.'] },
            { heading: 'Move work deliberately', paragraphs: ['Unfinished work should be completed, rescheduled, delegated or removed. Repeatedly copying it without a decision damages trust in the system.'] },
          ],
          { question: 'What should happen to repeatedly unfinished work?', options: ['Make a deliberate decision about it', 'Copy it forever without review', 'Hide it'], answer: 0, explanation: 'A trusted system requires explicit decisions.' }),
      ] },
    ],
    finalAssessment: { title: 'Time Management and Personal Productivity final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'Where should commitments be stored?', ['One trusted system', 'Only in memory', 'Random places'], 0, 'A trusted system reduces repeated remembering.'),
      assessmentQuestion('q2', 'What is a good next action?', ['Specific and achievable', 'Vague and enormous', 'Missing a verb'], 0, 'Specific actions reduce friction.'),
      assessmentQuestion('q3', 'What helps identify a material priority?', ['Consequence and dependency', 'The newest message only', 'Font size'], 0, 'Material consequences and blockers matter.'),
      assessmentQuestion('q4', 'Why limit work in progress?', ['To improve completion and reduce switching', 'To avoid responsibility', 'To create more lists'], 0, 'Too many open tasks dilute attention.'),
      assessmentQuestion('q5', 'What belongs in a focus block?', ['One defined outcome', 'Every notification', 'Several unrelated projects'], 0, 'Focused work needs a clear target.'),
      assessmentQuestion('q6', 'What should a weekly review achieve?', ['A current and trusted plan', 'More hidden tasks', 'No decisions'], 0, 'The review resets the system.'),
    ] },
    certificateStatement: 'Certificate of completion: Time Management and Personal Productivity.',
    importantNotice: 'Productivity methods should be adapted to disability, health, caring responsibilities, contractual duties and reasonable workplace adjustments.',
  },
];
