import { assessmentQuestion, lesson, type LibraryCourse } from './libraryCourseTypes';

const plusPlans = ['Learner Plus', 'Team 5', 'Team 15'] as const;

export const plusLibraryCourses: LibraryCourse[] = [
  {
    code: 'SME-CYB-101', slug: 'cybersecurity-awareness', title: 'Cybersecurity Awareness', category: 'Digital skills and AI',
    shortDescription: 'Reduce everyday risk from phishing, stolen credentials, unsafe devices and poor incident response.',
    overview: 'This awareness course helps learners recognise common cyber threats and take practical protective action. It covers social engineering, phishing-resistant sign-in, password managers, updates, device security, backups and immediate reporting after a suspected incident.',
    audience: ['Employees and volunteers using digital services', 'Small-business owners', 'Managers responsible for basic cyber awareness'],
    prerequisites: 'No technical knowledge is required.', level: 'Foundation', featured: true, version: '1.0', reviewDate: 'February 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Recognise phishing and social-engineering techniques.', 'Verify unusual requests through a separate trusted route.', 'Use stronger authentication and unique credentials.', 'Protect devices, software and backups.', 'Respond promptly to suspected compromise.', 'Explain why human reporting supports wider security controls.'],
    modules: [
      { id: 'threats', title: 'Module 1: Recognise common attacks', description: 'Understand how attackers create pressure and exploit normal behaviour.', lessons: [
        lesson('social-engineering', 'Social engineering and manipulation', 'Recognise urgency, authority, fear, reward and curiosity tactics.', 13,
          ['Identify manipulation techniques.', 'Pause before acting.', 'Use a separate verification route.'],
          [
            { heading: 'Attackers often target decisions rather than devices', paragraphs: ['A message may look professional and still be malicious. Attackers create urgency, imitate authority, offer an unexpected reward or threaten a negative consequence so that the recipient acts before checking.'] },
            { heading: 'Warning signs', bullets: ['Unexpected request for credentials, money or sensitive information.', 'Pressure to bypass a normal process.', 'A new bank account or payment destination.', 'A link that does not match the apparent sender.', 'Unusual wording, timing or behaviour from a known contact.'], callout: 'Verify important requests using contact details or systems you already trust, not the details supplied in the suspicious message.' },
          ],
          { question: 'What is the safest response to an unexpected urgent payment request?', options: ['Pay immediately', 'Verify it through a separate trusted route', 'Reply with your password'], answer: 1, explanation: 'Independent verification reduces the chance of acting on an impersonation attempt.' }),
        lesson('phishing', 'Phishing across email, text, calls and social media', 'Apply a consistent response to suspicious contact.', 13,
          ['Inspect context and destination.', 'Avoid interacting with suspicious content.', 'Report the attempt.'],
          [
            { heading: 'Phishing is not limited to email', paragraphs: ['Criminals may use texts, telephone calls, messaging apps, social media or collaboration tools. The channel changes, but the objective is often to obtain credentials, personal information, payment or access.'] },
            { heading: 'Safe handling sequence', bullets: ['Do not use the supplied link or telephone number.', 'Open the genuine service through a saved bookmark or known address.', 'Report the message using the approved route.', 'Delete it only after reporting or preserving required evidence.', 'If you interacted, report that fact immediately and follow recovery instructions.'] },
          ],
          { question: 'How should you open an account after receiving a suspicious link?', options: ['Use the link in the message', 'Use a known bookmark or type the genuine address independently', 'Forward the link to everybody'], answer: 1, explanation: 'Opening the genuine service independently avoids the supplied destination.' }),
      ] },
      { id: 'accounts', title: 'Module 2: Protect accounts and devices', description: 'Use stronger sign-in, approved software and recoverable data.', lessons: [
        lesson('authentication', 'Passwords, passkeys and multi-factor authentication', 'Reduce the harm caused by stolen credentials.', 14,
          ['Avoid password reuse.', 'Use a password manager.', 'Prefer stronger phishing-resistant methods where available.'],
          [
            { heading: 'One breach should not unlock every account', paragraphs: ['Use unique credentials for important services. A password manager can generate and store stronger passwords. Multi-factor authentication adds another requirement, while passkeys can provide stronger resistance to phishing where supported and approved.'] },
            { heading: 'Good account protection', bullets: ['Use the organisation’s approved sign-in method.', 'Enable multi-factor authentication where available.', 'Prefer passkeys or phishing-resistant methods when supported.', 'Never approve an unexpected sign-in notification.', 'Do not share authentication codes or recovery information.'] },
          ],
          { question: 'Why should passwords be unique?', options: ['So one leaked password does not expose several accounts', 'To make them easier to share', 'Because multi-factor authentication is unnecessary'], answer: 0, explanation: 'Unique credentials limit the spread of a compromise.' }),
        lesson('devices-backups', 'Updates, devices and backups', 'Reduce known vulnerabilities and support recovery.', 13,
          ['Install approved updates.', 'Protect unattended devices.', 'Understand the purpose of tested backups.'],
          [
            { heading: 'Basic controls work together', bullets: ['Apply operating-system and application updates promptly.', 'Lock devices whenever they are unattended.', 'Use approved software and storage locations.', 'Avoid unknown removable media and untrusted downloads.', 'Protect backups from the same incident affecting live data.'] },
            { heading: 'A backup is useful only if it can be restored', paragraphs: ['Important data should be backed up through an approved process. Recovery should be tested so that the organisation knows the data, permissions and systems can actually be restored.'] },
          ],
          { question: 'What makes a backup dependable?', options: ['It exists somewhere', 'It is protected and restoration has been tested', 'It uses the largest file name'], answer: 1, explanation: 'Recovery testing confirms the backup can be used after an incident.' }),
      ] },
      { id: 'respond', title: 'Module 3: Report and recover', description: 'Act quickly after suspicious activity or possible compromise.', lessons: [
        lesson('incident-response', 'Immediate incident response', 'Report suspected compromise without hiding, investigating beyond authority or destroying evidence.', 14,
          ['Recognise reportable indicators.', 'Preserve relevant information.', 'Follow containment instructions.'],
          [
            { heading: 'Report early', bullets: ['Unexpected sign-in or multi-factor prompt.', 'Credentials entered into a suspicious page.', 'Device lost, stolen or behaving unusually.', 'Sensitive information sent to the wrong recipient.', 'Malware warning or unauthorised software.', 'Unexplained payment or account change.'] },
            { heading: 'Do not make the incident harder to investigate', paragraphs: ['Do not conceal the mistake, delete evidence or independently contact an attacker. Follow the approved incident route and be accurate about what happened, what information was involved and what actions you already took.'] },
          ],
          { question: 'What should happen after credentials are entered into a suspicious site?', options: ['Report it immediately and follow recovery instructions', 'Wait to see what happens', 'Delete all messages and say nothing'], answer: 0, explanation: 'Early reporting allows credentials and sessions to be protected.' }),
        lesson('secure-habits', 'Build secure working habits', 'Make the safe action the normal action.', 11,
          ['Use approved processes.', 'Challenge bypass requests.', 'Support a reporting culture.'],
          [
            { heading: 'Security is operational behaviour', bullets: ['Verify payment and access changes.', 'Use approved sharing and storage tools.', 'Review permissions when roles change.', 'Keep personal and business accounts separate.', 'Discuss near misses so controls can improve.'] },
            { heading: 'A blame culture hides useful warning signs', paragraphs: ['People are more likely to report quickly when they know honest mistakes will be handled fairly. Deliberate misconduct can still be addressed, but routine awareness should encourage early disclosure and learning.'] },
          ],
          { question: 'Why is early reporting culture important?', options: ['It allows faster containment and learning', 'It guarantees no incidents', 'It removes the need for technical controls'], answer: 0, explanation: 'Human reporting complements technical detection and response.' }),
      ] },
    ],
    finalAssessment: { title: 'Cybersecurity Awareness final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'How should an unusual payment change be verified?', ['Through a separate trusted route', 'Using only the message reply button', 'It should not be verified'], 0, 'Independent verification reduces impersonation risk.'),
      assessmentQuestion('q2', 'What can phishing use?', ['Only email', 'Email, text, calls and other channels', 'Only printed letters'], 1, 'Phishing can arrive through many communication channels.'),
      assessmentQuestion('q3', 'Why use unique passwords?', ['To limit the spread of one compromise', 'To avoid multi-factor authentication', 'To make sharing easier'], 0, 'Unique credentials stop one leak exposing several accounts.'),
      assessmentQuestion('q4', 'What should happen to an unexpected MFA prompt?', ['Approve it', 'Reject it and report it if suspicious', 'Share it'], 1, 'An unexpected prompt may indicate attempted account access.'),
      assessmentQuestion('q5', 'When is a backup dependable?', ['After successful restoration testing', 'When its icon is visible', 'When nobody knows where it is'], 0, 'Testing demonstrates recoverability.'),
      assessmentQuestion('q6', 'What is the best response to a suspected compromise?', ['Report promptly and preserve information', 'Hide it', 'Investigate the attacker personally'], 0, 'Approved incident response should begin quickly.'),
    ] },
    certificateStatement: 'Certificate of completion: Cybersecurity Awareness.',
    importantNotice: 'This is general awareness training and does not replace organisation-specific security policies, technical controls, incident plans or specialist advice.',
    sources: [
      { label: 'National Cyber Security Centre: Phishing guidance', url: 'https://www.ncsc.gov.uk/section/respond-recover/phishing' },
      { label: 'National Cyber Security Centre: MFA for online services', url: 'https://www.ncsc.gov.uk/collection/mfa-for-your-corporate-online-services' },
      { label: 'National Cyber Security Centre: Passkeys', url: 'https://www.ncsc.gov.uk/passkeys' },
    ],
  },
  {
    code: 'SME-DAT-101', slug: 'uk-data-protection-awareness', title: 'UK Data Protection Awareness', category: 'Compliance awareness',
    shortDescription: 'Recognise personal data and handle it lawfully, fairly, securely and accountably.',
    overview: 'This awareness course introduces the everyday responsibilities that support UK data-protection compliance. It covers personal data, special category data, the seven principles, lawful and transparent handling, minimisation, accuracy, retention, security, individual rights and incident reporting.',
    audience: ['Staff and volunteers handling personal information', 'Small-business owners', 'Managers responsible for operational records'],
    prerequisites: 'No previous data-protection training is required.', level: 'Foundation', featured: true, version: '1.0', reviewDate: 'February 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Recognise personal and special category data.', 'Explain the data-protection principles.', 'Use information only for a defined and permitted purpose.', 'Apply minimisation, accuracy and retention controls.', 'Recognise rights requests and incidents.', 'Report concerns through the approved route.'],
    modules: [
      { id: 'foundations', title: 'Module 1: Data-protection foundations', description: 'Understand what information is protected and why context matters.', lessons: [
        lesson('personal-data', 'Personal data and sensitive information', 'Identify information relating to an identifiable living person.', 14,
          ['Recognise direct and indirect identifiers.', 'Understand special category data.', 'Consider identification in context.'],
          [
            { heading: 'Personal data is wider than names', paragraphs: ['Information may identify a person directly or when combined with other information. Examples can include contact details, identifiers, location information, online identifiers, opinions, photographs, employment records and customer history.'] },
            { heading: 'Additional care is required for sensitive information', bullets: ['Health information.', 'Racial or ethnic origin.', 'Religious or philosophical beliefs.', 'Trade-union membership.', 'Genetic or biometric data used for identification.', 'Sex life or sexual orientation.', 'Political opinions.'], callout: 'Criminal-offence information also has specific legal controls, although it is not classified as special category data.' },
          ],
          { question: 'Can information be personal data without containing a name?', options: ['Yes, if a person can still be identified', 'No, a name is always required', 'Only if it is printed'], answer: 0, explanation: 'Identification can arise from other identifiers or combinations of information.' }),
        lesson('principles', 'The data-protection principles', 'Use the seven principles as a practical decision framework.', 15,
          ['Name the principles.', 'Connect each principle to daily work.', 'Recognise accountability.'],
          [
            { heading: 'The seven principles', bullets: ['Lawfulness, fairness and transparency.', 'Purpose limitation.', 'Data minimisation.', 'Accuracy.', 'Storage limitation.', 'Integrity and confidentiality (security).', 'Accountability.'] },
            { heading: 'Principles work together', paragraphs: ['A record can be accurate but still collected unfairly. It can be secure but retained for too long. Staff should consider the whole lifecycle: why information is collected, how it is explained, who can use it, how it is protected and when it should be deleted or anonymised.'] },
          ],
          { question: 'Which principle requires an organisation to demonstrate compliance?', options: ['Accountability', 'Decoration', 'Profitability'], answer: 0, explanation: 'Accountability requires appropriate measures and evidence of compliance.' }),
      ] },
      { id: 'lifecycle', title: 'Module 2: Handle information through its lifecycle', description: 'Collect, use, share, correct and retain information appropriately.', lessons: [
        lesson('purpose-minimisation', 'Purpose, lawful handling and minimisation', 'Collect only what is needed for a defined and permitted purpose.', 15,
          ['Recognise the need for a lawful basis.', 'Avoid incompatible reuse.', 'Reduce unnecessary collection.'],
          [
            { heading: 'Purpose should drive the information', paragraphs: ['Before collecting personal data, the organisation should understand why it is needed, the lawful basis relied upon and what the person must be told. Staff should not reuse information for an unrelated purpose without checking that the new use is permitted.'] },
            { heading: 'Data minimisation questions', bullets: ['Is this field necessary for the defined purpose?', 'Could a less sensitive alternative achieve the same result?', 'Does every recipient need the full record?', 'Can information be anonymised or aggregated?', 'Are optional fields clearly optional?'] },
          ],
          { question: 'What should determine which personal data is collected?', options: ['The defined purpose and necessity', 'Curiosity', 'The number of available form fields'], answer: 0, explanation: 'Collection should be limited to information necessary for the purpose.' }),
        lesson('accuracy-retention-sharing', 'Accuracy, retention and sharing', 'Keep information reliable, time-limited and appropriately disclosed.', 15,
          ['Correct inaccurate records.', 'Apply retention rules.', 'Check sharing authority and security.'],
          [
            { heading: 'Accuracy is an active responsibility', paragraphs: ['The importance of accuracy depends on how the information is used. Staff should record the source, distinguish facts from opinions, correct known errors and avoid overwriting material history where an audit trail is required.'] },
            { heading: 'Before sharing', bullets: ['Confirm identity and authority.', 'Check the purpose and lawful basis.', 'Share only the information required.', 'Use an approved secure channel.', 'Record the disclosure where required.', 'Check any contract, agreement or internal procedure.'] },
            { heading: 'Retention is not “keep everything”', paragraphs: ['Information should be kept only as long as there is a justified legal, regulatory or operational reason. Retention schedules should identify the record type, period, trigger and disposal method.'] },
          ],
          { question: 'Which is part of safe data sharing?', options: ['Confirming recipient identity and authority', 'Sending the complete database by default', 'Using any convenient public channel'], answer: 0, explanation: 'Identity, authority, necessity and secure transmission should be checked.' }),
      ] },
      { id: 'people-incidents', title: 'Module 3: Rights, security and incidents', description: 'Recognise requests, protect information and report suspected breaches.', lessons: [
        lesson('rights-requests', 'Recognise individual rights requests', 'Identify requests even when the person does not use legal terminology.', 13,
          ['Recognise common rights.', 'Record receipt promptly.', 'Avoid obstructing or promising an outcome.'],
          [
            { heading: 'A request may be informal', paragraphs: ['A person might ask to see their information, correct it, delete it, restrict use, object, receive it in a portable form or challenge certain automated decisions. Staff should not require the person to quote legislation before recognising the request.'] },
            { heading: 'First-line response', bullets: ['Record the date and exact request.', 'Verify identity through the approved process.', 'Send it promptly to the responsible team or person.', 'Preserve relevant records.', 'Do not promise that every requested action will be granted.'] },
          ],
          { question: 'When should a rights request be recognised?', options: ['Only when it mentions UK GDPR', 'When the substance of the request concerns a relevant right', 'Only when submitted by a solicitor'], answer: 1, explanation: 'The wording is less important than the substance of the request.' }),
        lesson('security-breaches', 'Security and personal-data breaches', 'Recognise confidentiality, integrity and availability incidents.', 15,
          ['Identify possible breaches.', 'Report promptly.', 'Preserve evidence and follow instructions.'],
          [
            { heading: 'A breach is not only a leak', bullets: ['Information sent to the wrong recipient.', 'Lost or stolen device or paper record.', 'Unauthorised access or disclosure.', 'Data altered or corrupted without authority.', 'Important data unavailable when needed.', 'Ransomware or malicious deletion.'] },
            { heading: 'Immediate staff actions', paragraphs: ['Report the concern immediately through the approved route. Provide accurate facts, preserve relevant messages or logs and follow containment instructions. Do not conceal the incident, contact affected people without authority or decide alone whether regulatory notification is required.'] },
          ],
          { question: 'Which can be a personal-data breach?', options: ['Loss of availability as well as disclosure', 'Only a public website leak', 'Only an incident involving paper'], answer: 0, explanation: 'Breaches can affect confidentiality, integrity or availability.' }),
      ] },
    ],
    finalAssessment: { title: 'UK Data Protection Awareness final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What can make information personal data?', ['A person can be identified directly or indirectly', 'It contains a company logo', 'It is stored electronically'], 0, 'Identifiability is the key consideration.'),
      assessmentQuestion('q2', 'Which is a data-protection principle?', ['Data minimisation', 'Unlimited retention', 'Unrestricted reuse'], 0, 'Only necessary information should be collected and held.'),
      assessmentQuestion('q3', 'What should happen before a new use of personal data?', ['Check that the use is permitted and compatible', 'Assume every use is allowed', 'Remove all records'], 0, 'Purpose and lawful handling must be considered.'),
      assessmentQuestion('q4', 'What is required before sharing personal data?', ['Check identity, authority, necessity and security', 'Send everything', 'Use a personal account'], 0, 'Sharing must be controlled and proportionate.'),
      assessmentQuestion('q5', 'Must a rights request quote the law?', ['No', 'Yes, always', 'Only for correction'], 0, 'Requests are recognised by substance, not legal wording.'),
      assessmentQuestion('q6', 'What should staff do after a suspected breach?', ['Report promptly through the approved route', 'Hide it', 'Contact the regulator personally without authority'], 0, 'The organisation needs early information to assess and respond.'),
    ] },
    certificateStatement: 'Certificate of completion: UK Data Protection Awareness.',
    importantNotice: 'This is general awareness training and not legal advice. Learners must follow their organisation’s privacy notices, retention schedule, rights-request process, incident procedure and instructions from its data-protection lead or DPO.',
    sources: [
      { label: 'ICO: A guide to the data-protection principles', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/' },
      { label: 'ICO: Data minimisation', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/data-minimisation/' },
      { label: 'ICO: Training and awareness', url: 'https://ico.org.uk/for-organisations/advice-and-services/audits/data-protection-audit-framework/toolkits/training-and-awareness/' },
    ],
  },
  {
    code: 'SME-HS-101', slug: 'workplace-health-and-safety-awareness', title: 'Workplace Health and Safety Awareness', category: 'Safety awareness',
    shortDescription: 'Recognise hazards, understand risk controls and report incidents and near misses.',
    overview: 'This awareness course explains the difference between hazards and risks, how workplace risks are assessed, the hierarchy of controls, employee responsibilities, emergency arrangements and the value of reporting accidents, unsafe conditions and near misses.',
    audience: ['Employees and volunteers in general workplaces', 'New starters', 'Small-business owners requiring foundation awareness'],
    prerequisites: 'No prerequisites. This course does not replace role-specific or practical safety training.', level: 'Foundation', featured: true, version: '1.0', reviewDate: 'February 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Distinguish hazards from risks.', 'Identify who may be harmed and how.', 'Explain stronger and weaker controls.', 'Follow safe systems and emergency arrangements.', 'Report incidents and near misses.', 'Recognise when specialist training is required.'],
    modules: [
      { id: 'risk', title: 'Module 1: Understand workplace risk', description: 'Identify hazards and consider likelihood, severity and people affected.', lessons: [
        lesson('hazard-risk', 'Hazards and risks', 'Separate the source of potential harm from the chance and consequence of harm.', 13,
          ['Define hazard and risk.', 'Identify affected people.', 'Consider likelihood and severity.'],
          [
            { heading: 'Two different questions', bullets: ['Hazard: what could cause injury or ill health?', 'Risk: how likely is the harm and how serious could it be?'] },
            { heading: 'Look beyond the usual worker', paragraphs: ['Risk assessment should consider employees, contractors, visitors, customers, members of the public and people who may be particularly affected. Work patterns, disability, pregnancy, age, experience and lone working may change the risk or required controls.'] },
          ],
          { question: 'What is a hazard?', options: ['Something with the potential to cause harm', 'The likelihood of harm only', 'A completed training record'], answer: 0, explanation: 'A hazard is the source or situation with potential to cause harm.' }),
        lesson('risk-assessment', 'The risk-assessment process', 'Identify hazards, evaluate risk, control it, record and review.', 14,
          ['Describe the main steps.', 'Consult people doing the work.', 'Review after change or evidence of weakness.'],
          [
            { heading: 'A practical cycle', bullets: ['Identify hazards.', 'Decide who may be harmed and how.', 'Evaluate risk and existing controls.', 'Implement further controls where needed.', 'Record significant findings as required.', 'Review after change, incident, near miss or new information.'] },
            { heading: 'The people doing the work hold important evidence', paragraphs: ['Workers often know where procedures and reality differ. Consultation can reveal workarounds, maintenance problems, time pressure and near misses that are not visible from a desk review.'] },
          ],
          { question: 'When should a risk assessment be reviewed?', options: ['After material change, an incident or evidence controls may be inadequate', 'Never', 'Only when a website changes colour'], answer: 0, explanation: 'Reviews should respond to changes and evidence.' }),
      ] },
      { id: 'controls', title: 'Module 2: Control the risk', description: 'Prefer controls that remove or isolate the hazard over reliance on individual behaviour.', lessons: [
        lesson('hierarchy', 'The hierarchy of controls', 'Choose the most effective reasonably practicable control measures.', 15,
          ['Explain the control hierarchy.', 'Recognise the limits of PPE.', 'Use several controls where needed.'],
          [
            { heading: 'Stronger controls act closer to the hazard', bullets: ['Eliminate the hazard where possible.', 'Substitute for something less hazardous.', 'Use engineering or physical controls to isolate people.', 'Use administrative controls, procedures and training.', 'Use suitable personal protective equipment as part of the control system.'] },
            { heading: 'PPE is important but not the first answer to every risk', paragraphs: ['PPE depends on correct selection, fit, use, maintenance and human behaviour. It may be necessary, but stronger controls should be considered first and several controls may be needed together.'] },
          ],
          { question: 'Which control is generally considered before PPE?', options: ['Eliminating or isolating the hazard', 'Ignoring the hazard', 'Relying only on a warning'], answer: 0, explanation: 'Controls closer to the hazard are usually more dependable.' }),
        lesson('safe-working', 'Safe systems, competence and emergencies', 'Follow the approved method and know the limits of your competence.', 13,
          ['Use safe systems of work.', 'Stop and seek help when conditions change.', 'Follow emergency arrangements.'],
          [
            { heading: 'Training does not create unlimited competence', bullets: ['Use equipment only when trained and authorised.', 'Do not bypass guards or controls.', 'Check the work area and equipment before starting.', 'Stop if conditions differ from the plan.', 'Know alarms, exits, assembly points and first-aid arrangements.'] },
            { heading: 'Dynamic judgement has limits', paragraphs: ['Workers may need to respond to changing conditions, but they should not improvise beyond their authority or competence. Pause the task and escalate where the safe method is unclear.'] },
          ],
          { question: 'What should a worker do when conditions differ materially from the safe plan?', options: ['Pause and obtain appropriate guidance', 'Continue regardless', 'Disable the controls'], answer: 0, explanation: 'Changed conditions may require reassessment or a different method.' }),
      ] },
      { id: 'report', title: 'Module 3: Report and improve', description: 'Use incidents and observations to strengthen controls before further harm occurs.', lessons: [
        lesson('incidents', 'Accidents, incidents and near misses', 'Report what happened and preserve useful evidence.', 13,
          ['Recognise a near miss.', 'Use the approved reporting route.', 'Support investigation without blame or concealment.'],
          [
            { heading: 'Near misses are valuable warnings', paragraphs: ['A near miss is an event that did not cause harm but had the potential to do so. Reporting it can reveal a failed or missing control before somebody is injured.'] },
            { heading: 'Useful initial information', bullets: ['Time, location and activity.', 'People and equipment involved.', 'What was observed before and after.', 'Immediate actions taken.', 'Photographs or records where safe and authorised.', 'Witness details and relevant environmental conditions.'] },
          ],
          { question: 'Why should near misses be reported?', options: ['They can reveal weaknesses before harm occurs', 'They are never relevant', 'Only to increase paperwork'], answer: 0, explanation: 'Near misses provide evidence for preventive action.' }),
        lesson('safety-culture', 'Personal responsibility and safety culture', 'Challenge unsafe conditions and participate in improvement.', 11,
          ['Report concerns.', 'Follow controls consistently.', 'Avoid normalising unsafe shortcuts.'],
          [
            { heading: 'Normal work can drift away from the safe method', bullets: ['Time pressure encourages shortcuts.', 'Repeated success can create false confidence.', 'Broken equipment becomes “normal”.', 'New starters copy observed behaviour.', 'Near misses may not be discussed.'] },
            { heading: 'Speak up early', paragraphs: ['Use the organisation’s route to report unsafe conditions. An employee should not remove a control or continue work they reasonably believe presents serious danger without obtaining appropriate help. Emergency procedures and management instructions must be followed.'] },
          ],
          { question: 'What can make an unsafe shortcut seem acceptable?', options: ['Repeated use without an immediate injury', 'A completed risk assessment that prohibits it', 'A repair'], answer: 0, explanation: 'Lack of immediate harm can create false confidence.' }),
      ] },
    ],
    finalAssessment: { title: 'Workplace Health and Safety Awareness final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What is risk?', ['The likelihood and severity of harm from a hazard', 'Only the object causing harm', 'A training certificate'], 0, 'Risk considers likelihood and consequence.'),
      assessmentQuestion('q2', 'Who may need consideration in a risk assessment?', ['Anyone who may be affected', 'Only managers', 'Only visitors'], 0, 'All relevant groups and vulnerabilities should be considered.'),
      assessmentQuestion('q3', 'Which is highest in the control hierarchy?', ['Elimination', 'PPE', 'A poster'], 0, 'Removing the hazard is generally strongest.'),
      assessmentQuestion('q4', 'What should happen if the safe method no longer fits the conditions?', ['Pause and seek review', 'Continue regardless', 'Remove controls'], 0, 'Changed conditions may require reassessment.'),
      assessmentQuestion('q5', 'What is a near miss?', ['An event with potential for harm that did not cause harm', 'A successful inspection', 'A scheduled break'], 0, 'Near misses reveal potential risk.'),
      assessmentQuestion('q6', 'Why report unsafe conditions?', ['To support timely control and prevention', 'To avoid all work', 'To replace risk assessment'], 0, 'Reporting enables action and review.'),
    ] },
    certificateStatement: 'Certificate of completion: Workplace Health and Safety Awareness.',
    importantNotice: 'This course is general awareness only. It does not replace workplace induction, risk assessment, emergency drills, equipment training, first aid, manual handling, fire safety or other role-specific practical instruction.',
    sources: [
      { label: 'Health and Safety Executive: Managing risks and risk assessment at work', url: 'https://www.hse.gov.uk/simple-health-safety/risk/' },
      { label: 'Health and Safety Executive: Steps needed to manage risk', url: 'https://www.hse.gov.uk/simple-health-safety/risk/steps-needed-to-manage-risk.htm' },
      { label: 'Health and Safety Executive: Managing risk using PPE', url: 'https://www.hse.gov.uk/ppe/managing-risk-using-ppe.htm' },
    ],
  },
  {
    code: 'SME-EIR-101', slug: 'equality-inclusion-and-respect-at-work', title: 'Equality, Inclusion and Respect at Work', category: 'Workplace essentials',
    shortDescription: 'Support fair decisions, inclusive working practices and respectful professional behaviour.',
    overview: 'This awareness course introduces equality at work, protected characteristics, direct and indirect discrimination, harassment, victimisation, reasonable adjustments, inclusive communication and appropriate reporting. It focuses on everyday decisions and behaviour rather than abstract slogans.',
    audience: ['Employees and volunteers', 'Managers and team leaders', 'People involved in recruitment, service delivery or workplace decisions'],
    prerequisites: 'No prerequisites.', level: 'Foundation', featured: false, version: '1.0', reviewDate: 'February 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Recognise protected characteristics.', 'Distinguish common forms of discrimination.', 'Explain harassment and victimisation.', 'Use relevant and consistent decision criteria.', 'Support reasonable adjustments and inclusion.', 'Report concerns through appropriate routes.'],
    modules: [
      { id: 'law-conduct', title: 'Module 1: Equality and conduct', description: 'Understand the legal concepts and expected workplace behaviour.', lessons: [
        lesson('protected', 'Protected characteristics and discrimination', 'Recognise when treatment may be connected to a protected characteristic.', 15,
          ['Name the protected characteristics.', 'Distinguish direct and indirect discrimination.', 'Avoid irrelevant assumptions.'],
          [
            { heading: 'Protected characteristics under the Equality Act 2010', bullets: ['Age.', 'Disability.', 'Gender reassignment.', 'Marriage and civil partnership.', 'Pregnancy and maternity.', 'Race.', 'Religion or belief.', 'Sex.', 'Sexual orientation.'] },
            { heading: 'Different forms of discrimination', paragraphs: ['Direct discrimination involves less favourable treatment because of a protected characteristic. Indirect discrimination can arise when a provision, criterion or practice applies broadly but disadvantages a group and cannot be objectively justified. Other legal protections include harassment and victimisation.'] },
          ],
          { question: 'Can a rule applied to everybody still create discrimination risk?', options: ['Yes, if it disadvantages a protected group and is not justified', 'No, never', 'Only if it is unwritten'], answer: 0, explanation: 'A broadly applied practice may amount to indirect discrimination.' }),
        lesson('harassment-respect', 'Harassment, bullying and respectful conduct', 'Recognise unwanted behaviour and maintain professional boundaries.', 14,
          ['Recognise harassment risk.', 'Separate intent from impact and context.', 'Challenge conduct appropriately.'],
          [
            { heading: 'Intent is not the only consideration', paragraphs: ['A person may describe behaviour as a joke while another person experiences it as humiliating, hostile or offensive. Context, effect, repetition, power and the protected characteristic all matter.'] },
            { heading: 'Respectful conduct includes', bullets: ['Disagreeing without personal attack.', 'Avoiding degrading or exclusionary language.', 'Respecting names, pronouns and communication needs.', 'Not circulating offensive content.', 'Addressing concerns through fair procedures rather than retaliation.'] },
          ],
          { question: 'Does calling conduct a joke automatically make it acceptable?', options: ['No', 'Yes', 'Only in group chats'], answer: 0, explanation: 'The effect and context must be considered.' }),
      ] },
      { id: 'fairness', title: 'Module 2: Fair decisions and inclusion', description: 'Use relevant criteria and remove avoidable barriers.', lessons: [
        lesson('fair-decisions', 'Make fair and consistent decisions', 'Define criteria before deciding and record material reasons.', 14,
          ['Use relevant evidence.', 'Check consistency.', 'Identify assumptions and exceptions.'],
          [
            { heading: 'Fair does not always mean identical', paragraphs: ['People may require different support or adjustments to access the same opportunity. The decision should use criteria relevant to the role, service or objective and avoid assumptions based on protected characteristics.'] },
            { heading: 'Decision checks', bullets: ['Are the criteria necessary and clear?', 'Would the evidence support the same decision for a different person?', 'Could the process create an avoidable barrier?', 'Has an adjustment request been considered properly?', 'Are exceptions documented and justified?'] },
          ],
          { question: 'What makes a decision process stronger?', options: ['Relevant criteria and recorded reasons', 'Unrecorded personal instinct only', 'Different hidden criteria for each person'], answer: 0, explanation: 'Relevant and consistent criteria support fairness and accountability.' }),
        lesson('adjustments-inclusion', 'Reasonable adjustments and inclusive working', 'Identify barriers and consider effective practical changes.', 15,
          ['Recognise potential barriers.', 'Discuss adjustments respectfully.', 'Protect confidentiality.'],
          [
            { heading: 'Focus on the barrier and required outcome', bullets: ['Changes to equipment or software.', 'Alternative communication formats.', 'Changes to working arrangements or procedures.', 'Physical access changes.', 'Additional support or time.', 'Reallocation of a non-essential duty where appropriate.'] },
            { heading: 'Handle information carefully', paragraphs: ['A person should not be required to disclose more health or disability information than is needed for the adjustment process. Information should be shared only with people who need it for the defined purpose.'] },
          ],
          { question: 'What should adjustment discussions focus on?', options: ['The barrier and effective practical support', 'Personal curiosity', 'Making every role identical'], answer: 0, explanation: 'The aim is to remove or reduce disadvantage effectively.' }),
      ] },
      { id: 'respond', title: 'Module 3: Speak up and respond', description: 'Report concerns and manage them without retaliation or gossip.', lessons: [
        lesson('speaking-up', 'Raise and receive concerns', 'Use the appropriate route and respond without dismissing or prejudging.', 13,
          ['Know reporting options.', 'Listen and record carefully.', 'Avoid retaliation.'],
          [
            { heading: 'A person may raise a concern in several ways', bullets: ['Informal discussion with a manager.', 'Formal grievance or complaint.', 'Safeguarding or whistleblowing route where relevant.', 'Trade-union or employee-representative support.', 'External advice or legal process.'] },
            { heading: 'First response matters', paragraphs: ['Listen, avoid promising secrecy you cannot guarantee, explain the next steps and protect the person from retaliation. Do not conduct an unauthorised investigation or circulate the allegation.'] },
          ],
          { question: 'What should a manager avoid promising?', options: ['Absolute secrecy in every circumstance', 'A clear explanation of the process', 'A fair initial response'], answer: 0, explanation: 'Information may need to be shared with authorised people to address the concern.' }),
        lesson('inclusive-culture', 'Build an inclusive culture', 'Turn policy into everyday practice and review.', 12,
          ['Set behavioural expectations.', 'Use data and feedback responsibly.', 'Act on recurring barriers.'],
          [
            { heading: 'Culture is created by repeated decisions', bullets: ['Recruitment and progression criteria.', 'Meeting access and participation.', 'Work allocation and development opportunities.', 'Social events and informal networks.', 'Response to inappropriate behaviour.', 'Whether people can raise concerns safely.'] },
            { heading: 'Measure with care', paragraphs: ['Workforce information can help identify patterns, but it must be collected and used lawfully, interpreted cautiously and combined with qualitative feedback. A numerical difference does not by itself explain the cause.'] },
          ],
          { question: 'What best demonstrates inclusion?', options: ['Consistent practices that remove barriers and address concerns', 'A slogan only', 'Ignoring feedback'], answer: 0, explanation: 'Inclusion is reflected in everyday systems and behaviour.' }),
      ] },
    ],
    finalAssessment: { title: 'Equality, Inclusion and Respect at Work final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'How many protected characteristics are listed in the Equality Act 2010?', ['Nine', 'Three', 'Twenty'], 0, 'The Act lists nine protected characteristics.'),
      assessmentQuestion('q2', 'Can an apparently neutral practice create disadvantage?', ['Yes', 'No', 'Only if verbal'], 0, 'Indirect discrimination can involve a broadly applied practice.'),
      assessmentQuestion('q3', 'What matters when considering harassment?', ['Context and effect as well as intent', 'Only the speaker’s intention', 'Only whether it was written'], 0, 'Impact and context are relevant.'),
      assessmentQuestion('q4', 'Does fair treatment always mean identical treatment?', ['No, adjustments may be required', 'Yes, always', 'Only for managers'], 0, 'Different support can be necessary to remove disadvantage.'),
      assessmentQuestion('q5', 'What should happen after a concern is raised?', ['Use the appropriate fair process and protect against retaliation', 'Circulate it widely', 'Dismiss it immediately'], 0, 'Concerns require controlled and fair handling.'),
      assessmentQuestion('q6', 'Where is inclusion demonstrated?', ['Everyday decisions and practices', 'Only a policy title', 'Only an annual event'], 0, 'Culture is reflected in repeated behaviour and systems.'),
    ] },
    certificateStatement: 'Certificate of completion: Equality, Inclusion and Respect at Work.',
    importantNotice: 'This is general awareness training and not legal advice. Organisation-specific equality, grievance, disciplinary, safeguarding, whistleblowing and reasonable-adjustment processes must be followed.',
    sources: [
      { label: 'Acas: Discrimination and the Equality Act 2010', url: 'https://www.acas.org.uk/discrimination-and-the-law' },
      { label: 'Acas: Making your workplace inclusive', url: 'https://www.acas.org.uk/improving-equality-diversity-and-inclusion/making-your-workplace-inclusive' },
      { label: 'Acas: Preventing discrimination', url: 'https://www.acas.org.uk/what-an-employer-can-do-to-prevent-discrimination' },
    ],
  },
  {
    code: 'SME-MKT-101', slug: 'marketing-fundamentals', title: 'Marketing Fundamentals', category: 'Business and enterprise',
    shortDescription: 'Create a focused offer, choose useful channels and measure meaningful customer action.',
    overview: 'This course covers positioning, audience research, the customer journey, message design, channel selection, campaign planning and performance measures. It helps learners move away from vanity metrics and connect marketing activity to a defined business objective.',
    audience: ['Small-business owners', 'New marketing assistants', 'People promoting a service, product or project'], prerequisites: 'A product, service or project to use as a working example is helpful.',
    level: 'Foundation', featured: false, version: '1.0', reviewDate: 'August 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Define a target audience and position.', 'Map a customer journey.', 'Create messages based on outcomes and evidence.', 'Select channels based on audience behaviour.', 'Build a simple campaign plan.', 'Use measures connected to decisions.'],
    modules: [
      { id: 'position', title: 'Module 1: Audience and positioning', description: 'Know who the offer is for and why it should matter.', lessons: [
        lesson('audience', 'Define a useful audience', 'Use behaviour, need and context rather than an imaginary “everyone”.', 13,
          ['Segment the audience.', 'Identify the buying situation.', 'Gather customer evidence.'],
          [
            { heading: 'A useful segment shares a relevant characteristic', bullets: ['A common problem or desired outcome.', 'A similar buying context or trigger.', 'A reachable channel or community.', 'A realistic ability and authority to buy.', 'Comparable objections or decision criteria.'] },
            { heading: 'Research behaviour, not stereotypes', paragraphs: ['Use interviews, service records, search behaviour, enquiries and purchase data. Avoid assuming needs solely from demographic characteristics when behaviour and context provide better evidence.'] },
          ],
          { question: 'What makes an audience segment useful?', options: ['Shared relevant needs and buying context', 'Everybody is included', 'It is based only on a guess'], answer: 0, explanation: 'A useful segment supports a focused offer and route to market.' }),
        lesson('positioning', 'Position the offer', 'Explain the category, outcome, evidence and difference.', 13,
          ['Draft a positioning statement.', 'Distinguish features and outcomes.', 'Support claims with evidence.'],
          [
            { heading: 'A positioning statement answers', bullets: ['Who is this for?', 'What problem or job does it address?', 'What kind of solution is it?', 'What outcome does it create?', 'Why should the audience believe or choose it?'] },
            { heading: 'Claims should be supportable', paragraphs: ['Avoid absolute claims such as “best” or “guaranteed” unless they are accurate, fair and properly evidenced. Specific proof, demonstrations, case studies and clear terms are more useful than vague superlatives.'] },
          ],
          { question: 'Which message is strongest?', options: ['We are amazing', 'We help independent retailers reconcile marketplace orders in one weekly report', 'Everybody needs us'], answer: 1, explanation: 'It identifies an audience, task and outcome.' }),
      ] },
      { id: 'journey', title: 'Module 2: Journey, message and channels', description: 'Make the next step clear at each stage of the decision.', lessons: [
        lesson('customer-journey', 'Map the customer journey', 'Identify questions and barriers from awareness to retention.', 14,
          ['Define journey stages.', 'Identify information needs.', 'Reduce friction.'],
          [
            { heading: 'Typical stages', bullets: ['Awareness: the person recognises a problem or opportunity.', 'Consideration: they compare approaches and providers.', 'Decision: they need confidence, terms and a clear action.', 'Onboarding: they need to begin successfully.', 'Use and retention: they judge whether the promised value appears.'] },
            { heading: 'Marketing does not end at purchase', paragraphs: ['Poor onboarding and unclear support can destroy the value created by an effective campaign. Retention, referral and repeat purchase depend on the delivered experience.'] },
          ],
          { question: 'Which stage follows purchase?', options: ['Onboarding and use', 'Awareness again only', 'No further customer experience'], answer: 0, explanation: 'Successful onboarding supports value and retention.' }),
        lesson('channels-content', 'Choose channels and content', 'Match channel choice to customer behaviour and message purpose.', 14,
          ['Evaluate channel fit.', 'Create content for a defined stage.', 'Avoid spreading resources too thinly.'],
          [
            { heading: 'Channel selection factors', bullets: ['Where the audience already seeks information.', 'Whether the offer needs explanation or demonstration.', 'Cost and internal capacity.', 'Ability to track relevant action.', 'Rules, permissions and platform dependence.', 'Speed of learning and feedback.'] },
            { heading: 'Content should perform a job', paragraphs: ['A guide may help a person understand a problem. A comparison page may support consideration. A demonstration may build confidence. A clear checkout or enquiry form supports action. Choose the content job before the format.'] },
          ],
          { question: 'What should determine the content format?', options: ['The customer’s stage and information need', 'The newest trend only', 'The longest possible word count'], answer: 0, explanation: 'Content should support a specific customer decision or action.' }),
      ] },
      { id: 'measure', title: 'Module 3: Campaign and measurement', description: 'Plan activity with an objective, budget, owner and review method.', lessons: [
        lesson('campaign-plan', 'Build a simple campaign plan', 'Connect audience, proposition, activity and resources.', 13,
          ['Write a campaign objective.', 'Define the offer and call to action.', 'Assign budget and ownership.'],
          [
            { heading: 'Minimum campaign plan', bullets: ['Objective and business reason.', 'Audience and evidence.', 'Proposition and offer.', 'Message and proof.', 'Channels and content.', 'Budget, owner and timing.', 'Conversion action and follow-up.', 'Measures and review date.'] },
            { heading: 'Operational readiness matters', paragraphs: ['Do not create demand the organisation cannot fulfil safely. Confirm stock, appointment capacity, support, payment, terms and complaint handling before increasing promotion.'] },
          ],
          { question: 'What should be confirmed before increasing demand?', options: ['Operational capacity and customer journey', 'Only the logo', 'Nothing'], answer: 0, explanation: 'Marketing should not overwhelm delivery and support.' }),
        lesson('measurement', 'Measure what supports a decision', 'Connect metrics to the objective and customer journey.', 13,
          ['Distinguish vanity and decision metrics.', 'Use conversion measures.', 'Review quality as well as quantity.'],
          [
            { heading: 'Useful measures may include', bullets: ['Qualified enquiries.', 'Conversion rate.', 'Cost per acquired customer.', 'Average order value.', 'Activation or onboarding completion.', 'Retention, repeat purchase or cancellation.', 'Customer complaints and support demand.'] },
            { heading: 'Numbers need context', paragraphs: ['A large number of views may not matter if the audience is wrong or no useful action follows. Compare results with the objective, cost, quality and operational impact.'] },
          ],
          { question: 'Which metric is most connected to commercial action?', options: ['Qualified enquiry conversion', 'Page background colour', 'Raw impressions with no context'], answer: 0, explanation: 'Conversion connects audience action to the objective.' }),
      ] },
    ],
    finalAssessment: { title: 'Marketing Fundamentals final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What defines a useful segment?', ['Relevant shared need and buying context', 'Every possible person', 'A random label'], 0, 'Segmentation should support a focused decision.'),
      assessmentQuestion('q2', 'What belongs in positioning?', ['Audience, problem, outcome and reason to believe', 'Only a slogan', 'Only the price'], 0, 'Positioning explains relevance and difference.'),
      assessmentQuestion('q3', 'Does the journey end at purchase?', ['No', 'Yes', 'Only online'], 0, 'Onboarding and delivery affect retention.'),
      assessmentQuestion('q4', 'What should channel choice reflect?', ['Audience behaviour and message purpose', 'Personal preference only', 'The largest platform'], 0, 'Channel fit supports effectiveness.'),
      assessmentQuestion('q5', 'What must be ready before increasing demand?', ['Delivery and support capacity', 'Nothing', 'A second logo'], 0, 'Operational failure can undermine marketing.'),
      assessmentQuestion('q6', 'Which is a decision metric?', ['Qualified enquiry conversion', 'Unexplained impressions', 'Number of font styles'], 0, 'It connects activity to useful action.'),
    ] },
    certificateStatement: 'Certificate of completion: Marketing Fundamentals.',
    importantNotice: 'Marketing activity must comply with applicable advertising, consumer, privacy, electronic-communications and platform requirements. This course does not provide legal advice.',
  },
  {
    code: 'SME-FIN-101', slug: 'bookkeeping-and-cash-flow-basics', title: 'Bookkeeping and Cash-Flow Basics', category: 'Business and enterprise',
    shortDescription: 'Keep reliable transaction records and understand the timing of money entering and leaving a small business.',
    overview: 'This foundation course explains source documents, income and expense records, categories, reconciliation, invoices, receivables, payables, profit, cash flow, basic forecasting and month-end review. It is designed to improve operational understanding rather than train professional accountants.',
    audience: ['Sole traders and small-business owners', 'Administrative staff supporting finance records', 'New managers reading basic business information'],
    prerequisites: 'Basic numeracy and access to a calculator are helpful.', level: 'Foundation', featured: false, version: '1.0', reviewDate: 'August 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Recognise common source documents.', 'Record income and expenses consistently.', 'Reconcile records to bank and payment statements.', 'Distinguish profit from cash.', 'Prepare a simple cash-flow forecast.', 'Use a month-end review checklist.'],
    modules: [
      { id: 'records', title: 'Module 1: Reliable records', description: 'Create an organised evidence trail for business transactions.', lessons: [
        lesson('source-documents', 'Source documents and transaction records', 'Keep evidence that explains what each transaction was and why it occurred.', 13,
          ['Identify source documents.', 'Record transactions consistently.', 'Separate business and personal activity.'],
          [
            { heading: 'Typical source documents', bullets: ['Sales invoices and receipts.', 'Supplier invoices and receipts.', 'Bank and card statements.', 'Payment-provider reports.', 'Contracts and purchase orders.', 'Credit notes, refunds and expense claims.'] },
            { heading: 'A transaction record should be understandable later', paragraphs: ['Record date, amount, party, category, tax treatment where relevant, payment status and the link to supporting evidence. Use a consistent numbering and storage system.'] },
          ],
          { question: 'What is the purpose of a source document?', options: ['To evidence and explain a transaction', 'To decorate the accounts', 'To replace every bank statement'], answer: 0, explanation: 'Source documents support the accuracy and audit trail of records.' }),
        lesson('categories-controls', 'Categories and basic controls', 'Use consistent classifications and protect the integrity of records.', 13,
          ['Apply consistent categories.', 'Use approval and access controls.', 'Preserve corrections.'],
          [
            { heading: 'Consistency supports comparison', paragraphs: ['Using the same categories each month makes trends and unusual movements easier to identify. Categories should be detailed enough for decision-making without becoming impossible to maintain.'] },
            { heading: 'Basic record controls', bullets: ['Restrict access to authorised people.', 'Separate approval and payment where practicable.', 'Keep an audit trail of corrections.', 'Review unusual or duplicate transactions.', 'Back up records through an approved process.'] },
          ],
          { question: 'Why use consistent categories?', options: ['To support comparison and review', 'To hide transactions', 'To avoid reconciliation'], answer: 0, explanation: 'Consistent categories make trends and errors easier to identify.' }),
      ] },
      { id: 'reconcile', title: 'Module 2: Reconcile and manage amounts due', description: 'Compare records to external statements and track money owed.', lessons: [
        lesson('reconciliation', 'Bank and payment reconciliation', 'Explain differences between internal records and external statements.', 15,
          ['Match transactions.', 'Identify timing differences.', 'Investigate unexplained items.'],
          [
            { heading: 'Reconciliation is a comparison', bullets: ['Match recorded receipts and payments to statements.', 'Account for fees, refunds and chargebacks.', 'Identify duplicated, missing or miscategorised entries.', 'Record deposits or payments still in transit.', 'Investigate differences rather than forcing the totals to agree.'] },
            { heading: 'Evidence should support the correction', paragraphs: ['If a record is changed, preserve who changed it, when, why and the evidence used. Deleting the original history can weaken the audit trail.'] },
          ],
          { question: 'What should happen to an unexplained reconciliation difference?', options: ['Investigate it', 'Force the totals to match', 'Ignore it permanently'], answer: 0, explanation: 'Differences may indicate missing records, timing or error.' }),
        lesson('receivables-payables', 'Invoices, receivables and payables', 'Track what customers owe and what the business must pay.', 14,
          ['Issue clear invoices.', 'Monitor overdue amounts.', 'Plan upcoming liabilities.'],
          [
            { heading: 'A clear invoice supports payment', bullets: ['Supplier identity and contact details.', 'Customer and service details.', 'Invoice date and unique number.', 'Amount, tax and total as applicable.', 'Payment due date and method.', 'Relevant purchase-order or contract reference.'] },
            { heading: 'Amounts due affect cash planning', paragraphs: ['Review overdue customer balances and upcoming supplier, tax, payroll, finance and subscription payments. A sale is not available cash until it has been collected.'] },
          ],
          { question: 'Why monitor receivables?', options: ['To understand money customers still owe', 'To calculate website visits', 'To remove supplier invoices'], answer: 0, explanation: 'Receivables affect available cash and collection work.' }),
      ] },
      { id: 'cash', title: 'Module 3: Profit, cash and review', description: 'Understand timing and use a simple forecast to protect liquidity.', lessons: [
        lesson('profit-cash', 'Profit is not the same as cash', 'Understand the difference between performance and available money.', 14,
          ['Describe timing differences.', 'Recognise non-cash and future obligations.', 'Protect working capital.'],
          [
            { heading: 'Timing creates the difference', bullets: ['A sale may be recognised before payment arrives.', 'A supplier cost may be incurred before it is paid.', 'Loan repayments may include capital and interest.', 'Tax may become payable after the period that generated it.', 'Asset purchases may affect cash differently from reported profit.'] },
            { heading: 'Cash keeps the business operating', paragraphs: ['A business needs enough available money to meet obligations when due. Strong sales do not remove the need for collection, reserves and forecast review.'] },
          ],
          { question: 'Can a profitable business have a cash shortage?', options: ['Yes', 'No', 'Only if it has no customers'], answer: 0, explanation: 'Profit and cash can arise at different times.' }),
        lesson('forecast-review', 'Cash-flow forecast and month-end review', 'Look ahead and investigate material changes.', 15,
          ['Build a simple weekly or monthly forecast.', 'Use realistic timing.', 'Complete a review checklist.'],
          [
            { heading: 'A simple forecast contains', bullets: ['Opening cash balance.', 'Expected receipts by realistic date.', 'Expected payments by due date.', 'Tax, payroll and finance commitments.', 'One-off and seasonal items.', 'Closing cash and minimum reserve.'] },
            { heading: 'Month-end review', bullets: ['Complete reconciliations.', 'Review overdue invoices and bills.', 'Check unusual income and expenses.', 'Compare actual results with forecast.', 'Update the next forecast.', 'Prepare information required by the accountant or tax adviser.'] },
          ],
          { question: 'What should forecast receipts use?', options: ['Realistic expected payment dates', 'Invoice dates only regardless of behaviour', 'No dates'], answer: 0, explanation: 'A cash forecast needs realistic timing.' }),
      ] },
    ],
    finalAssessment: { title: 'Bookkeeping and Cash-Flow Basics final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What supports a transaction record?', ['A source document', 'A guess', 'A logo'], 0, 'Evidence supports accuracy and explanation.'),
      assessmentQuestion('q2', 'Why preserve an audit trail?', ['To show changes and reasons', 'To hide corrections', 'To avoid controls'], 0, 'An audit trail supports accountability.'),
      assessmentQuestion('q3', 'What does reconciliation compare?', ['Internal records and external statements', 'Two advertisements', 'Employee holidays only'], 0, 'Reconciliation checks completeness and accuracy.'),
      assessmentQuestion('q4', 'What is a receivable?', ['Money owed by a customer', 'A supplier payment already made', 'A website visitor'], 0, 'Receivables are customer amounts due.'),
      assessmentQuestion('q5', 'Is profit identical to available cash?', ['No', 'Yes', 'Always after one day'], 0, 'Timing and accounting treatment create differences.'),
      assessmentQuestion('q6', 'What belongs in a cash forecast?', ['Expected receipts and payments by realistic date', 'Only annual sales', 'No opening balance'], 0, 'Timing of cash movement is central.'),
    ] },
    certificateStatement: 'Certificate of completion: Bookkeeping and Cash-Flow Basics.',
    importantNotice: 'This course is educational and does not provide accounting, tax, audit, insolvency, credit or investment advice. Professional advice may be required for the learner’s circumstances.',
  },
  {
    code: 'SME-CRT-201', slug: 'critical-thinking-and-better-decisions', title: 'Critical Thinking and Better Decisions', category: 'Personal development',
    shortDescription: 'Separate evidence from assumption, test alternatives and create defensible decision records.',
    overview: 'This intermediate course provides a practical method for examining claims, sources, uncertainty, bias, causation, options and trade-offs. Learners use decision records and review points to improve accountability and learn from outcomes without relying on hindsight.',
    audience: ['Managers and decision-makers', 'Analysts and project staff', 'People reviewing proposals, incidents or business cases'], prerequisites: 'Learners should be comfortable reading short workplace scenarios and comparing written evidence.',
    level: 'Intermediate', featured: false, version: '1.0', reviewDate: 'August 2027', includedPlans: [...plusPlans],
    learningOutcomes: ['Separate fact, inference, assumption and opinion.', 'Assess source relevance and reliability.', 'Generate and test alternative explanations.', 'Recognise common reasoning errors.', 'Compare options using explicit criteria.', 'Create and review a decision record.'],
    modules: [
      { id: 'evidence', title: 'Module 1: Claims and evidence', description: 'Understand what is known, how it is known and what remains uncertain.', lessons: [
        lesson('claim-types', 'Facts, inferences, assumptions and opinions', 'Label the status of information before using it.', 14,
          ['Distinguish information types.', 'Make uncertainty visible.', 'Avoid presenting inference as fact.'],
          [
            { heading: 'Four useful labels', bullets: ['Fact: supported by direct evidence or a reliable record.', 'Inference: a conclusion drawn from evidence.', 'Assumption: treated as true for the purpose of analysis but not established.', 'Opinion: a judgement or preference.'] },
            { heading: 'The label may change as evidence develops', paragraphs: ['An initial incident report may contain allegations and assumptions. Investigation can confirm some points, disprove others and leave uncertainty. A good record preserves that development.'] },
          ],
          { question: 'What is an inference?', options: ['A conclusion drawn from evidence', 'A directly observed fact only', 'A random preference'], answer: 0, explanation: 'An inference goes beyond the evidence and should be labelled as a conclusion.' }),
        lesson('source-quality', 'Evaluate source quality', 'Judge relevance, proximity, expertise, independence and corroboration.', 14,
          ['Check source origin.', 'Consider incentives and limitations.', 'Seek corroboration.'],
          [
            { heading: 'Source questions', bullets: ['How close is the source to the event or data?', 'Does the source have relevant expertise?', 'Is the information current and complete?', 'What incentive or conflict may affect it?', 'Can the claim be checked against another independent source?', 'Is the source appropriate for the seriousness of the decision?'] },
            { heading: 'Authority should match the question', paragraphs: ['A regulator may be authoritative on its legal guidance, a system log on a recorded event and a subject-matter expert on professional interpretation. No source is automatically reliable for every type of claim.'] },
          ],
          { question: 'What strengthens a factual claim?', options: ['Independent corroboration', 'Repeating it more confidently', 'Removing the source'], answer: 0, explanation: 'Independent evidence reduces reliance on one potentially weak source.' }),
      ] },
      { id: 'reasoning', title: 'Module 2: Test the reasoning', description: 'Challenge preferred explanations and avoid common thinking traps.', lessons: [
        lesson('alternatives', 'Generate alternative explanations', 'Ask what else could explain the same evidence.', 15,
          ['Avoid premature closure.', 'Identify disconfirming evidence.', 'Compare explanations.'],
          [
            { heading: 'Do not stop at the first plausible answer', bullets: ['List at least two alternative explanations.', 'Identify evidence each explanation predicts.', 'Look for evidence that would disprove the preferred explanation.', 'Consider whether several causes may operate together.', 'State what remains unknown.'] },
            { heading: 'Correlation is not automatically causation', paragraphs: ['Two things occurring together may reflect coincidence, a third factor, reverse causation or a genuine causal link. A causal claim needs an explanation and evidence appropriate to the context.'] },
          ],
          { question: 'What is a good way to test a preferred explanation?', options: ['Look for evidence that could disprove it', 'Ignore alternatives', 'Treat correlation as proof'], answer: 0, explanation: 'Disconfirming evidence challenges confirmation bias.' }),
        lesson('bias-errors', 'Bias and reasoning errors', 'Recognise predictable ways judgement can become distorted.', 15,
          ['Recognise confirmation and anchoring effects.', 'Avoid outcome bias.', 'Use structured challenge.'],
          [
            { heading: 'Common risks', bullets: ['Confirmation bias: favouring evidence that supports the preferred answer.', 'Anchoring: relying too heavily on the first number or explanation.', 'Availability: overestimating vivid or recent examples.', 'Sunk-cost effect: continuing because resources have already been spent.', 'Outcome bias: judging the original decision only by the result.'] },
            { heading: 'Use process controls', paragraphs: ['Define criteria before seeing all options, invite an independent challenge, record uncertainty and separate the quality of the decision process from luck in the outcome.'] },
          ],
          { question: 'What is confirmation bias?', options: ['Favouring information that supports an existing view', 'Checking opposing evidence', 'Using explicit criteria'], answer: 0, explanation: 'Confirmation bias narrows attention to supportive evidence.' }),
      ] },
      { id: 'decide', title: 'Module 3: Decide and learn', description: 'Compare options, document rationale and review outcomes fairly.', lessons: [
        lesson('options-criteria', 'Compare options and trade-offs', 'Use criteria that reflect objectives, constraints and risk.', 15,
          ['Define decision criteria.', 'Weight material factors.', 'Identify reversibility and downside.'],
          [
            { heading: 'A useful comparison includes', bullets: ['Expected benefit.', 'Cost and capacity.', 'Legal, safety, customer and security risk.', 'Time and dependencies.', 'Reversibility and exit route.', 'Impact on different people.', 'Evidence strength and uncertainty.'] },
            { heading: 'Precision should match evidence', paragraphs: ['A detailed numerical score can create false confidence if the inputs are weak. Use ranges, scenarios and sensitivity checks where exact values are not justified.'] },
          ],
          { question: 'Why can a detailed score be misleading?', options: ['Weak assumptions may be hidden behind precise numbers', 'Numbers are never useful', 'Criteria should be secret'], answer: 0, explanation: 'Precision does not repair weak evidence.' }),
        lesson('decision-record', 'Create and review a decision record', 'Make context, evidence, authority and review points visible.', 15,
          ['Record the rationale.', 'Define success and review date.', 'Learn without hindsight distortion.'],
          [
            { heading: 'Decision-record fields', bullets: ['Decision and owner.', 'Purpose and authority.', 'Options considered.', 'Evidence, assumptions and uncertainty.', 'Criteria and trade-offs.', 'Risks and controls.', 'Expected result and success measure.', 'Review date and triggers for reconsideration.'] },
            { heading: 'Review the process and outcome separately', paragraphs: ['A sound decision can have a poor outcome because of uncertainty, while a weak decision can succeed through luck. Review what was knowable at the time and update the process with new evidence.'] },
          ],
          { question: 'What should a decision review avoid?', options: ['Assuming the outcome alone proves the original process was good or bad', 'Comparing the result with expectations', 'Identifying new evidence'], answer: 0, explanation: 'Outcome bias ignores the information and uncertainty present at the time.' }),
      ] },
    ],
    finalAssessment: { title: 'Critical Thinking and Better Decisions final assessment', instructions: 'Answer all six questions. A score of 80% or higher is required.', passMark: 80, questions: [
      assessmentQuestion('q1', 'What is an assumption?', ['Something treated as true but not established', 'A directly verified fact', 'A completed action'], 0, 'Assumptions should be visible and tested.'),
      assessmentQuestion('q2', 'What strengthens source confidence?', ['Relevant independent corroboration', 'A confident tone', 'No evidence'], 0, 'Corroboration reduces dependence on one source.'),
      assessmentQuestion('q3', 'Why generate alternatives?', ['To avoid premature closure', 'To make decisions impossible', 'To remove evidence'], 0, 'Alternatives test whether the preferred explanation is uniquely supported.'),
      assessmentQuestion('q4', 'What is anchoring?', ['Over-reliance on the first number or explanation', 'Reviewing assumptions', 'Seeking new evidence'], 0, 'The initial reference point can distort later judgement.'),
      assessmentQuestion('q5', 'What should comparison criteria reflect?', ['Objectives, constraints and material risks', 'Personal preference only', 'The longest option'], 0, 'Criteria should connect to the decision purpose.'),
      assessmentQuestion('q6', 'Why record a review date?', ['To compare results with expectations and reconsider when needed', 'To prevent learning', 'To hide the decision'], 0, 'Review turns the decision into a learning process.'),
    ] },
    certificateStatement: 'Certificate of completion: Critical Thinking and Better Decisions.',
    importantNotice: 'This course supports general decision quality. It does not replace professional expertise, statutory decision procedures, consultation duties or specialist legal, financial, medical, safeguarding, safety or technical advice.',
  },
];
